package com.leateck.model.processPackItemObject;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

/**
 * Generated interface definition for application table LC_UserProcessPackItem.
 * Application table description: <br>
 * @ftps.exclude 
 */
public interface IMESLCUserProcessPackItem extends IMESGeneratedLCUserProcessPackItem {
}