package com.leateck.phase.accountalternativematerial0010;

/**
 * This file is generated by the PhaseLibManager
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.objects.MESATObjectFilter;
import com.rockwell.mes.commons.base.ifc.services.PCContext;
import com.rockwell.mes.services.s88.ifc.execution.IMESRtPhase;

import com.datasweep.compatibility.client.MeasuredValue;


/**
 * Generated class definition
 */
public abstract class MESGeneratedRtPhaseDataMatAlterAcct0010Filter extends MESATObjectFilter  {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    private static final String ATDEFINITION_NAME = "LC_PhDatMatAlterAcct0010";

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESGeneratedRtPhaseDataMatAlterAcct0010Filter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated method definition
     *
     */
    public MESGeneratedRtPhaseDataMatAlterAcct0010Filter() {
        super(PCContext.getServerImpl(), ATDEFINITION_NAME);
    }

    /**
     * Generated method definition
     *
     * @return the list of the objects
     */
    @Override     
    public List<MESRtPhaseDataMatAlterAcct0010> getFilteredObjects () {
        return MESATObject.getFilteredMESATObjectList(this, MESRtPhaseDataMatAlterAcct0010.class);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forParentEqualTo(IMESRtPhase value) //
            throws DatasweepException {
        String columnName = MESRtPhaseDataMatAlterAcct0010.COL_NAME_PARENT;
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo(columnName, Long.valueOf(value.getKey()));
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forParentNotEqualTo(IMESRtPhase value) //
            throws DatasweepException {
        String columnName = MESRtPhaseDataMatAlterAcct0010.COL_NAME_PARENT;
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo(columnName, Long.valueOf(value.getKey()));
    }



    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialIDEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_materialID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialIDNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_materialID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialIDContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_materialID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialIDStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_materialID", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMfcPosEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_mfcPos", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMfcPosNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_mfcPos", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMfcPosContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_mfcPos", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMfcPosStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_mfcPos", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIsHeaderEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_isHeader", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIsHeaderNotEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_isHeader", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialDescriptionEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_materialDescription", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialDescriptionNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_materialDescription", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialDescriptionContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_materialDescription", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forMaterialDescriptionStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_materialDescription", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forBatchIDEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_batchID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forBatchIDNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_batchID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forBatchIDContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_batchID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forBatchIDStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_batchID", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSublotIDEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_sublotID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSublotIDNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_sublotID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSublotIDContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_sublotID", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSublotIDStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_sublotID", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIdentifiedQtyEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_identifiedQty", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIdentifiedQtyNotEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_identifiedQty", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forConsumedQtyEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_consumedQty", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forConsumedQtyNotEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_consumedQty", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forWastedQtyEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_wastedQty", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forWastedQtyNotEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_wastedQty", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSampledQtyEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_sampledQty", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forSampledQtyNotEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_sampledQty", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forReturnedQtyEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_returnedQty", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forReturnedQtyNotEqualTo(MeasuredValue value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_returnedQty", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forPlannedQtyWithLimitsEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_plannedQtyWithLimits", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forPlannedQtyWithLimitsNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_plannedQtyWithLimits", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forPlannedQtyWithLimitsContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_plannedQtyWithLimits", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forPlannedQtyWithLimitsStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_plannedQtyWithLimits", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forAccountingStatusEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_accountingStatus", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forAccountingStatusNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_accountingStatus", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forAccountingStatusContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_accountingStatus", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forAccountingStatusStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_accountingStatus", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forResultEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_result", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forResultNotEqualTo(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_result", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forResultContaining(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameContaining("SC_result", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forResultStartingWith(String value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameStartingWith("SC_result", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIsModifiedEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameEqualTo("SC_isModified", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseDataMatAlterAcct0010Filter forIsModifiedNotEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseDataMatAlterAcct0010Filter) forColumnNameNotEqualTo("SC_isModified", value);
    }

}
