package com.leateck.phase.accountalternativematerial0010;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutputFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputMatAlterAcct0010Filter extends MESGeneratedRtPhaseOutputMatAlterAcct0010Filter //nl
                                                                implements IMESRtPhaseOutputFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseOutputMatAlterAcct0010Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseOutputMatAlterAcct0010Filter() {
        super();
    }
}
