package com.leateck.phase.identifyequipment0100;

/**
 * This file is generated by the PhaseGenerator
 *
 * Please do not modify this file manually !!
 */

import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.services.s88.ifc.processdata.MESRtPhaseData;

import com.rockwell.mes.commons.base.ifc.utility.StringUtilsEx;
import com.rockwell.mes.services.s88equipment.ifc.IMESS88Equipment; 
import com.rockwell.mes.commons.base.ifc.objects.MESATObjectReferenceFieldHandler;

 /**
 * Generated class definition
 * <br/>Application table: RS_PhDatIdentEq0100
 */
public abstract class MESGeneratedRtPhaseDataIdentEq0100
 extends MESRtPhaseData {

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "RS_PhDatIdentEq0100";

    /** Generated reference field handler */
    private final MESATObjectReferenceFieldHandler<IMESS88Equipment> refEqObject = 
            MESATObjectReferenceFieldHandler.createReferenceFieldHandler(this, IMESS88Equipment.class, "RS_eqObject");

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedRtPhaseDataIdentEq0100(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source the source to copy.
     */
    public MESGeneratedRtPhaseDataIdentEq0100(MESGeneratedRtPhaseDataIdentEq0100 source) {
        super(source);

        this.refEqObject.initFromCopyConstructor(source.refEqObject);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedRtPhaseDataIdentEq0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated constructor
     */
    public MESGeneratedRtPhaseDataIdentEq0100() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();

        this.refEqObject.synchronizeAfterATRowRefresh();
    }    
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEqReqClassId() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_eqReqClassId"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqReqClassId(String value) {
        String oldValue = this.getEqReqClassId();
        this.dgtATRow.setValue("RS_eqReqClassId", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("eqReqClassId", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEqReqClassShortDesc() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_eqReqClassShortDesc"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqReqClassShortDesc(String value) {
        String oldValue = this.getEqReqClassShortDesc();
        this.dgtATRow.setValue("RS_eqReqClassShortDesc", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("eqReqClassShortDesc", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEqReqType() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_eqReqType"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqReqType(String value) {
        String oldValue = this.getEqReqType();
        this.dgtATRow.setValue("RS_eqReqType", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("eqReqType", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEqId() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_eqId"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqId(String value) {
        String oldValue = this.getEqId();
        this.dgtATRow.setValue("RS_eqId", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("eqId", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEqShortDesc() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_eqShortDesc"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqShortDesc(String value) {
        String oldValue = this.getEqShortDesc();
        this.dgtATRow.setValue("RS_eqShortDesc", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("eqShortDesc", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getScannedEqId() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_scannedEqId"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setScannedEqId(String value) {
        String oldValue = this.getScannedEqId();
        this.dgtATRow.setValue("RS_scannedEqId", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("scannedEqId", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getScannedEqShortDesc() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_scannedEqShortDesc"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setScannedEqShortDesc(String value) {
        String oldValue = this.getScannedEqShortDesc();
        this.dgtATRow.setValue("RS_scannedEqShortDesc", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("scannedEqShortDesc", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getGroupParentId() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_groupParentId"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setGroupParentId(String value) {
        String oldValue = this.getGroupParentId();
        this.dgtATRow.setValue("RS_groupParentId", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("groupParentId", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getGroupParentShortDesc() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("RS_groupParentShortDesc"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setGroupParentShortDesc(String value) {
        String oldValue = this.getGroupParentShortDesc();
        this.dgtATRow.setValue("RS_groupParentShortDesc", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("groupParentShortDesc", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getEqReqPropVals() {
        return (byte[]) this.dgtATRow.getValue("RS_eqReqPropVals");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqReqPropVals(byte[] value) {
        byte[] oldValue = this.getEqReqPropVals();
        this.dgtATRow.setValue("RS_eqReqPropVals", value);
        pcs.firePropertyChange("eqReqPropVals", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getEqReqPropValsStates() {
        return (byte[]) this.dgtATRow.getValue("RS_eqReqPropValsStates");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqReqPropValsStates(byte[] value) {
        byte[] oldValue = this.getEqReqPropValsStates();
        this.dgtATRow.setValue("RS_eqReqPropValsStates", value);
        pcs.firePropertyChange("eqReqPropValsStates", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getEqIdentPropVals() {
        return (byte[]) this.dgtATRow.getValue("RS_eqIdentPropVals");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqIdentPropVals(byte[] value) {
        byte[] oldValue = this.getEqIdentPropVals();
        this.dgtATRow.setValue("RS_eqIdentPropVals", value);
        pcs.firePropertyChange("eqIdentPropVals", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getEqIdentPropValsStates() {
        return (byte[]) this.dgtATRow.getValue("RS_eqIdentPropValsStates");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqIdentPropValsStates(byte[] value) {
        byte[] oldValue = this.getEqIdentPropValsStates();
        this.dgtATRow.setValue("RS_eqIdentPropValsStates", value);
        pcs.firePropertyChange("eqIdentPropValsStates", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getChildGridData() {
        return (byte[]) this.dgtATRow.getValue("RS_childGridData");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setChildGridData(byte[] value) {
        byte[] oldValue = this.getChildGridData();
        this.dgtATRow.setValue("RS_childGridData", value);
        pcs.firePropertyChange("childGridData", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public byte[] getEqPropertyList() {
        return (byte[]) this.dgtATRow.getValue("RS_eqPropertyList");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqPropertyList(byte[] value) {
        byte[] oldValue = this.getEqPropertyList();
        this.dgtATRow.setValue("RS_eqPropertyList", value);
        pcs.firePropertyChange("eqPropertyList", oldValue, value);
    }

    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public IMESS88Equipment getEqObject() {
        return this.refEqObject.getReference();
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEqObject(IMESS88Equipment value) {
        this.refEqObject.setReference(value, pcs, "eqObject");
    }

    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();

        this.refEqObject.prepareATRowForSave(res);

        return res;
    }

}
