package com.leateck.model.processPackRecordObject;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

/**
 * Generated interface definition for application table LC_UserProcessPackRecord.
 * Application table description: <br>
 * @ftps.exclude 
 */
public interface IMESLCUserProcessPackRecord extends IMESGeneratedLCUserProcessPackRecord {
}