package com.leateck.model.processPackRecordObject;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table LC_UserProcessPackRecord.<BR>
 * Application table description: 
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedLCUserProcessPackRecord extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "LC_UserProcessPackRecord";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_COMMENTS = "comments";

    /** Generated column name */
    public static final String SQL_COL_NAME_COMMENTS = "comments_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_COMMENTS = "comments";

    /** Generated property name */
    public static final String PROP_NAME_OPERATOR = "operator";

    /** Generated column name */
    public static final String SQL_COL_NAME_OPERATOR = "operator_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_OPERATOR = "operator";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKIDES = "processPackIDes";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKIDES = "processPackIDes_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKIDES = "processPackIDes";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKIDE = "processPackIde";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKIDE = "processPackIde_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKIDE = "processPackIde";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKSTATE = "processPackState";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKSTATE = "processPackState_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKSTATE = "processPackState";

    /** Generated property name */
    public static final String PROP_NAME_STATETIME = "stateTime";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATETIME_UTC = "stateTime_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STATETIME = "stateTime";

    /** Generated property name */
    public static final String PROP_NAME_VERSION = "version";

    /** Generated column name */
    public static final String SQL_COL_NAME_VERSION = "version_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_VERSION = "version";

    /**
     * Generated getter for column comments.<BR>
     * Column description: 签名注释
     * 
     * @return the requested value
     */
    public String getComments();

    /**
     * Generated setter for column comments.<BR>
     * Column description: 签名注释
     * 
     * @param value The new value to be assigned
     */
    public void setComments(String value);

    /**
     * Generated getter for column operator.<BR>
     * Column description: 操作人
     * 
     * @return the requested value
     */
    public String getOperator();

    /**
     * Generated setter for column operator.<BR>
     * Column description: 操作人
     * 
     * @param value The new value to be assigned
     */
    public void setOperator(String value);

    /**
     * Generated getter for column processPackIDes.<BR>
     * Column description: 工艺包描述
     * 
     * @return the requested value
     */
    public String getProcessPackIDes();

    /**
     * Generated setter for column processPackIDes.<BR>
     * Column description: 工艺包描述
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackIDes(String value);

    /**
     * Generated getter for column processPackIde.<BR>
     * Column description: 工艺包标识符
     * 
     * @return the requested value
     */
    public String getProcessPackIde();

    /**
     * Generated setter for column processPackIde.<BR>
     * Column description: 工艺包标识符
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackIde(String value);

    /**
     * Generated getter for column processPackState.<BR>
     * Column description: 工艺包状态
     * 
     * @return the requested value
     */
    public Long getProcessPackState();

    /**
     * Generated setter for column processPackState.<BR>
     * Column description: 工艺包状态
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackState(Long value);

    /**
     * Generated getter for column stateTime.<BR>
     * Column description: 状态时间
     * 
     * @return the requested value
     */
    public Time getStateTime();

    /**
     * Generated setter for column stateTime.<BR>
     * Column description: 状态时间
     * 
     * @param value The new value to be assigned
     */
    public void setStateTime(Time value);

    /**
     * Generated getter for column version.<BR>
     * Column description: 工艺包版本
     * 
     * @return the requested value
     */
    public String getVersion();

    /**
     * Generated setter for column version.<BR>
     * Column description: 工艺包版本
     * 
     * @param value The new value to be assigned
     */
    public void setVersion(String value);

}