package com.leateck.model.processPackRecordObject;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */

/**
 * Generated filter interface for application table LC_UserProcessPackRecord.
 * @ftps.exclude 
 */
public interface IMESLCUserProcessPackRecordFilter extends IMESGeneratedLCUserProcessPackRecordFilter {
}
