package com.leateck.parameter.materialpositioncontrol0010;

/**
 * This file is generated by ParameterClassManager
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.services.PCContext;


/**
 * Generated class definition
 */
public abstract class MESGeneratedRtParamMatPosiControl0100Filter extends MESGeneratedParamMatPosiControl0100Filter  {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    private static final String ATDEFINITION_NAME = "LC_RtParMatPosiControl0100";

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESGeneratedRtParamMatPosiControl0100Filter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated method definition
     *
     */
    public MESGeneratedRtParamMatPosiControl0100Filter() {
        super(PCContext.getServerImpl(), ATDEFINITION_NAME);
    }
}
