package com.leateck.parameter.materialpositioncontrol0010;

/**
 * This file is generated by ParameterClassManager
 */
import com.datasweep.compatibility.client.Server;

/**
 * Generated class definition
 */
public class MESParamMatPosiControl0100Filter extends MESGeneratedParamMatPosiControl0100Filter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESParamMatPosiControl0100Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESParamMatPosiControl0100Filter() {
        super();
    }
}
