package com.leateck.phase.wdmaterialidentification0100;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutputFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputWDMatIdent0010Filter extends MESGeneratedRtPhaseOutputWDMatIdent0010Filter //nl
                                                                implements IMESRtPhaseOutputFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseOutputWDMatIdent0010Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseOutputWDMatIdent0010Filter() {
        super();
    }
}
