package com.leateck.phase.wdmaterialidentification0100;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutput;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputWDMatIdent0010 extends MESGeneratedRtPhaseOutputWDMatIdent0010 implements IMESRtPhaseOutput {

    /**
     * Generated constructor (from DB key)
     *
     * @param key The key of the ATRow to load.
     */
    public MESRtPhaseOutputWDMatIdent0010(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESRtPhaseOutputWDMatIdent0010(MESRtPhaseOutputWDMatIdent0010 source) {
        super(source);
    }

    /**
     * Generated constructor (from ATRow)
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESRtPhaseOutputWDMatIdent0010(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESRtPhaseOutputWDMatIdent0010() {
        super();
    }

    public void setIdentificationResult(IdentificationResult0610 result) {
        super.setResult(result.toString());
    }

    public IdentificationResult0610 getIdentificationResult() {
        return IdentificationResult0610.valueOf(super.getResult());
    }
}
