package com.leateck.parameter.sequencerule0010;

/**
 * This file is generated by ParameterClassManager
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.recipe.IMESProcessParameterData;

/**
 * Generated class definition
 */
public class MESParamSeqRule0100 extends MESGeneratedParamSeqRule0100 //nl
                                                  implements IMESProcessParameterData {

    /**
     * Generated method definition
     *
     * @param key The key of the ATRow to load.
     */
    public MESParamSeqRule0100(long key) {
        super(key);
    }

    /**
     * Generated method definition
     *
     * @param source the source to copy.
     */
    public MESParamSeqRule0100(MESParamSeqRule0100 source) {
        super(source);
    }

    /**
     * Generated method definition
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESParamSeqRule0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated method definition
     *
     */
    public MESParamSeqRule0100() {
        super();
    }

    /**
     * {@inheritDoc}
     * @see IMESProcessParameterData#getDataAsString()
     */
    public String getDataAsString() {
        // TASK: implement!
        return "";
    }
}
