package com.leateck.phase.sclRecordEBR0020.AT;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table SCL_IF_RecordEBRData.<BR>
 * Application table description: Record EBR phase同步插入改AT表用于接口处理等,避免对PhaseData表的轮询及操作
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedSCLIFRecordEBRData extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "SCL_IF_RecordEBRData";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_ERPPROCESSFLAG = "erpProcessFlag";

    /** Generated column name */
    public static final String SQL_COL_NAME_ERPPROCESSFLAG = "erpProcessFlag_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_ERPPROCESSFLAG = "erpProcessFlag";

    /** Generated property name */
    public static final String PROP_NAME_EXECUTEOPR = "executeOpr";

    /** Generated column name */
    public static final String SQL_COL_NAME_EXECUTEOPR = "executeOpr_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_EXECUTEOPR = "executeOpr";

    /** Generated property name */
    public static final String PROP_NAME_LIMSPROCESSFLAG = "limsProcessFlag";

    /** Generated column name */
    public static final String SQL_COL_NAME_LIMSPROCESSFLAG = "limsProcessFlag_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_LIMSPROCESSFLAG = "limsProcessFlag";

    /** Generated property name */
    public static final String PROP_NAME_MESPROCESSFLAG = "mesProcessFlag";

    /** Generated column name */
    public static final String SQL_COL_NAME_MESPROCESSFLAG = "mesProcessFlag_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MESPROCESSFLAG = "mesProcessFlag";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY1 = "mvKey1";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY1 = "mvKey1_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY1 = "mvKey1";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY10 = "mvKey10";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY10 = "mvKey10_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY10 = "mvKey10";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY11 = "mvKey11";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY11 = "mvKey11_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY11 = "mvKey11";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY12 = "mvKey12";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY12 = "mvKey12_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY12 = "mvKey12";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY13 = "mvKey13";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY13 = "mvKey13_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY13 = "mvKey13";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY14 = "mvKey14";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY14 = "mvKey14_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY14 = "mvKey14";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY15 = "mvKey15";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY15 = "mvKey15_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY15 = "mvKey15";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY16 = "mvKey16";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY16 = "mvKey16_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY16 = "mvKey16";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY17 = "mvKey17";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY17 = "mvKey17_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY17 = "mvKey17";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY18 = "mvKey18";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY18 = "mvKey18_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY18 = "mvKey18";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY19 = "mvKey19";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY19 = "mvKey19_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY19 = "mvKey19";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY2 = "mvKey2";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY2 = "mvKey2_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY2 = "mvKey2";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY20 = "mvKey20";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY20 = "mvKey20_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY20 = "mvKey20";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY3 = "mvKey3";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY3 = "mvKey3_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY3 = "mvKey3";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY4 = "mvKey4";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY4 = "mvKey4_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY4 = "mvKey4";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY5 = "mvKey5";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY5 = "mvKey5_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY5 = "mvKey5";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY6 = "mvKey6";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY6 = "mvKey6_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY6 = "mvKey6";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY7 = "mvKey7";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY7 = "mvKey7_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY7 = "mvKey7";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY8 = "mvKey8";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY8 = "mvKey8_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY8 = "mvKey8";

    /** Generated property name */
    public static final String PROP_NAME_MVKEY9 = "mvKey9";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVKEY9 = "mvKey9_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVKEY9 = "mvKey9";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM1 = "mvUom1";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM1 = "mvUom1_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM1 = "mvUom1";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM10 = "mvUom10";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM10 = "mvUom10_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM10 = "mvUom10";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM11 = "mvUom11";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM11 = "mvUom11_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM11 = "mvUom11";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM12 = "mvUom12";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM12 = "mvUom12_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM12 = "mvUom12";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM13 = "mvUom13";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM13 = "mvUom13_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM13 = "mvUom13";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM14 = "mvUom14";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM14 = "mvUom14_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM14 = "mvUom14";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM15 = "mvUom15";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM15 = "mvUom15_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM15 = "mvUom15";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM16 = "mvUom16";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM16 = "mvUom16_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM16 = "mvUom16";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM17 = "mvUom17";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM17 = "mvUom17_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM17 = "mvUom17";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM18 = "mvUom18";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM18 = "mvUom18_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM18 = "mvUom18";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM19 = "mvUom19";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM19 = "mvUom19_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM19 = "mvUom19";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM2 = "mvUom2";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM2 = "mvUom2_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM2 = "mvUom2";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM20 = "mvUom20";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM20 = "mvUom20_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM20 = "mvUom20";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM3 = "mvUom3";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM3 = "mvUom3_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM3 = "mvUom3";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM4 = "mvUom4";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM4 = "mvUom4_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM4 = "mvUom4";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM5 = "mvUom5";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM5 = "mvUom5_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM5 = "mvUom5";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM6 = "mvUom6";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM6 = "mvUom6_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM6 = "mvUom6";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM7 = "mvUom7";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM7 = "mvUom7_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM7 = "mvUom7";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM8 = "mvUom8";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM8 = "mvUom8_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM8 = "mvUom8";

    /** Generated property name */
    public static final String PROP_NAME_MVUOM9 = "mvUom9";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVUOM9 = "mvUom9_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVUOM9 = "mvUom9";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE1 = "mvValue1";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE1 = "mvValue1_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE1 = "mvValue1";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE10 = "mvValue10";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE10 = "mvValue10_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE10 = "mvValue10";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE11 = "mvValue11";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE11 = "mvValue11_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE11 = "mvValue11";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE12 = "mvValue12";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE12 = "mvValue12_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE12 = "mvValue12";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE13 = "mvValue13";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE13 = "mvValue13_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE13 = "mvValue13";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE14 = "mvValue14";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE14 = "mvValue14_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE14 = "mvValue14";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE15 = "mvValue15";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE15 = "mvValue15_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE15 = "mvValue15";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE16 = "mvValue16";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE16 = "mvValue16_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE16 = "mvValue16";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE17 = "mvValue17";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE17 = "mvValue17_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE17 = "mvValue17";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE18 = "mvValue18";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE18 = "mvValue18_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE18 = "mvValue18";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE19 = "mvValue19";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE19 = "mvValue19_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE19 = "mvValue19";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE2 = "mvValue2";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE2 = "mvValue2_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE2 = "mvValue2";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE20 = "mvValue20";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE20 = "mvValue20_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE20 = "mvValue20";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE3 = "mvValue3";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE3 = "mvValue3_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE3 = "mvValue3";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE4 = "mvValue4";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE4 = "mvValue4_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE4 = "mvValue4";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE5 = "mvValue5";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE5 = "mvValue5_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE5 = "mvValue5";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE6 = "mvValue6";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE6 = "mvValue6_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE6 = "mvValue6";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE7 = "mvValue7";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE7 = "mvValue7_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE7 = "mvValue7";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE8 = "mvValue8";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE8 = "mvValue8_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE8 = "mvValue8";

    /** Generated property name */
    public static final String PROP_NAME_MVVALUE9 = "mvValue9";

    /** Generated column name */
    public static final String SQL_COL_NAME_MVVALUE9 = "mvValue9_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MVVALUE9 = "mvValue9";

    /** Generated property name */
    public static final String PROP_NAME_ORDERNUMBER = "orderNumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_ORDERNUMBER = "orderNumber_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_ORDERNUMBER = "orderNumber";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSFLAG = "processFlag";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSFLAG = "processFlag_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSFLAG = "processFlag";

    /** Generated property name */
    public static final String PROP_NAME_RTPHASEKEY = "rtPhaseKey";

    /** Generated column name */
    public static final String SQL_COL_NAME_RTPHASEKEY = "rtPhaseKey_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_RTPHASEKEY = "rtPhaseKey";

    /** Generated property name */
    public static final String PROP_NAME_SIGKEY = "sigKey";

    /** Generated column name */
    public static final String SQL_COL_NAME_SIGKEY = "sigKey_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_SIGKEY = "sigKey";

    /** Generated property name */
    public static final String PROP_NAME_STATIONNAME = "stationName";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATIONNAME = "stationName_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STATIONNAME = "stationName";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY1 = "stringKey1";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY1 = "stringKey1_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY1 = "stringKey1";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY10 = "stringKey10";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY10 = "stringKey10_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY10 = "stringKey10";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY11 = "stringKey11";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY11 = "stringKey11_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY11 = "stringKey11";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY12 = "stringKey12";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY12 = "stringKey12_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY12 = "stringKey12";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY13 = "stringKey13";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY13 = "stringKey13_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY13 = "stringKey13";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY14 = "stringKey14";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY14 = "stringKey14_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY14 = "stringKey14";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY15 = "stringKey15";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY15 = "stringKey15_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY15 = "stringKey15";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY16 = "stringKey16";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY16 = "stringKey16_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY16 = "stringKey16";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY17 = "stringKey17";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY17 = "stringKey17_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY17 = "stringKey17";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY18 = "stringKey18";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY18 = "stringKey18_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY18 = "stringKey18";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY19 = "stringKey19";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY19 = "stringKey19_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY19 = "stringKey19";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY2 = "stringKey2";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY2 = "stringKey2_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY2 = "stringKey2";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY20 = "stringKey20";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY20 = "stringKey20_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY20 = "stringKey20";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY3 = "stringKey3";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY3 = "stringKey3_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY3 = "stringKey3";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY4 = "stringKey4";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY4 = "stringKey4_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY4 = "stringKey4";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY5 = "stringKey5";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY5 = "stringKey5_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY5 = "stringKey5";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY6 = "stringKey6";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY6 = "stringKey6_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY6 = "stringKey6";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY7 = "stringKey7";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY7 = "stringKey7_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY7 = "stringKey7";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY8 = "stringKey8";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY8 = "stringKey8_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY8 = "stringKey8";

    /** Generated property name */
    public static final String PROP_NAME_STRINGKEY9 = "stringKey9";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGKEY9 = "stringKey9_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGKEY9 = "stringKey9";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE1 = "stringValue1";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE1 = "stringValue1_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE1 = "stringValue1";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE10 = "stringValue10";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE10 = "stringValue10_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE10 = "stringValue10";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE11 = "stringValue11";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE11 = "stringValue11_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE11 = "stringValue11";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE12 = "stringValue12";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE12 = "stringValue12_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE12 = "stringValue12";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE13 = "stringValue13";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE13 = "stringValue13_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE13 = "stringValue13";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE14 = "stringValue14";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE14 = "stringValue14_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE14 = "stringValue14";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE15 = "stringValue15";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE15 = "stringValue15_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE15 = "stringValue15";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE16 = "stringValue16";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE16 = "stringValue16_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE16 = "stringValue16";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE17 = "stringValue17";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE17 = "stringValue17_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE17 = "stringValue17";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE18 = "stringValue18";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE18 = "stringValue18_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE18 = "stringValue18";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE19 = "stringValue19";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE19 = "stringValue19_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE19 = "stringValue19";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE2 = "stringValue2";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE2 = "stringValue2_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE2 = "stringValue2";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE20 = "stringValue20";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE20 = "stringValue20_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE20 = "stringValue20";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE3 = "stringValue3";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE3 = "stringValue3_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE3 = "stringValue3";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE4 = "stringValue4";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE4 = "stringValue4_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE4 = "stringValue4";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE5 = "stringValue5";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE5 = "stringValue5_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE5 = "stringValue5";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE6 = "stringValue6";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE6 = "stringValue6_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE6 = "stringValue6";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE7 = "stringValue7";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE7 = "stringValue7_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE7 = "stringValue7";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE8 = "stringValue8";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE8 = "stringValue8_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE8 = "stringValue8";

    /** Generated property name */
    public static final String PROP_NAME_STRINGVALUE9 = "stringValue9";

    /** Generated column name */
    public static final String SQL_COL_NAME_STRINGVALUE9 = "stringValue9_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STRINGVALUE9 = "stringValue9";

    /** Generated property name */
    public static final String PROP_NAME_WMSPROCESSFLAG = "wmsProcessFlag";

    /** Generated column name */
    public static final String SQL_COL_NAME_WMSPROCESSFLAG = "wmsProcessFlag_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_WMSPROCESSFLAG = "wmsProcessFlag";

    /**
     * Generated getter for column erpProcessFlag.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public Long getErpProcessFlag();

    /**
     * Generated setter for column erpProcessFlag.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setErpProcessFlag(Long value);

    /**
     * Generated getter for column executeOpr.<BR>
     * Column description: 操作人
     * 
     * @return the requested value
     */
    public String getExecuteOpr();

    /**
     * Generated setter for column executeOpr.<BR>
     * Column description: 操作人
     * 
     * @param value The new value to be assigned
     */
    public void setExecuteOpr(String value);

    /**
     * Generated getter for column limsProcessFlag.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public Long getLimsProcessFlag();

    /**
     * Generated setter for column limsProcessFlag.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setLimsProcessFlag(Long value);

    /**
     * Generated getter for column mesProcessFlag.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public Long getMesProcessFlag();

    /**
     * Generated setter for column mesProcessFlag.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMesProcessFlag(Long value);

    /**
     * Generated getter for column mvKey1.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey1();

    /**
     * Generated setter for column mvKey1.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey1(String value);

    /**
     * Generated getter for column mvKey10.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey10();

    /**
     * Generated setter for column mvKey10.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey10(String value);

    /**
     * Generated getter for column mvKey11.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey11();

    /**
     * Generated setter for column mvKey11.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey11(String value);

    /**
     * Generated getter for column mvKey12.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey12();

    /**
     * Generated setter for column mvKey12.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey12(String value);

    /**
     * Generated getter for column mvKey13.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey13();

    /**
     * Generated setter for column mvKey13.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey13(String value);

    /**
     * Generated getter for column mvKey14.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey14();

    /**
     * Generated setter for column mvKey14.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey14(String value);

    /**
     * Generated getter for column mvKey15.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey15();

    /**
     * Generated setter for column mvKey15.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey15(String value);

    /**
     * Generated getter for column mvKey16.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey16();

    /**
     * Generated setter for column mvKey16.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey16(String value);

    /**
     * Generated getter for column mvKey17.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey17();

    /**
     * Generated setter for column mvKey17.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey17(String value);

    /**
     * Generated getter for column mvKey18.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey18();

    /**
     * Generated setter for column mvKey18.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey18(String value);

    /**
     * Generated getter for column mvKey19.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey19();

    /**
     * Generated setter for column mvKey19.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey19(String value);

    /**
     * Generated getter for column mvKey2.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey2();

    /**
     * Generated setter for column mvKey2.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey2(String value);

    /**
     * Generated getter for column mvKey20.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey20();

    /**
     * Generated setter for column mvKey20.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey20(String value);

    /**
     * Generated getter for column mvKey3.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey3();

    /**
     * Generated setter for column mvKey3.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey3(String value);

    /**
     * Generated getter for column mvKey4.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey4();

    /**
     * Generated setter for column mvKey4.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey4(String value);

    /**
     * Generated getter for column mvKey5.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey5();

    /**
     * Generated setter for column mvKey5.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey5(String value);

    /**
     * Generated getter for column mvKey6.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey6();

    /**
     * Generated setter for column mvKey6.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey6(String value);

    /**
     * Generated getter for column mvKey7.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey7();

    /**
     * Generated setter for column mvKey7.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey7(String value);

    /**
     * Generated getter for column mvKey8.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey8();

    /**
     * Generated setter for column mvKey8.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey8(String value);

    /**
     * Generated getter for column mvKey9.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvKey9();

    /**
     * Generated setter for column mvKey9.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvKey9(String value);

    /**
     * Generated getter for column mvUom1.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom1();

    /**
     * Generated setter for column mvUom1.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom1(String value);

    /**
     * Generated getter for column mvUom10.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom10();

    /**
     * Generated setter for column mvUom10.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom10(String value);

    /**
     * Generated getter for column mvUom11.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom11();

    /**
     * Generated setter for column mvUom11.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom11(String value);

    /**
     * Generated getter for column mvUom12.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom12();

    /**
     * Generated setter for column mvUom12.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom12(String value);

    /**
     * Generated getter for column mvUom13.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom13();

    /**
     * Generated setter for column mvUom13.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom13(String value);

    /**
     * Generated getter for column mvUom14.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom14();

    /**
     * Generated setter for column mvUom14.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom14(String value);

    /**
     * Generated getter for column mvUom15.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom15();

    /**
     * Generated setter for column mvUom15.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom15(String value);

    /**
     * Generated getter for column mvUom16.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom16();

    /**
     * Generated setter for column mvUom16.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom16(String value);

    /**
     * Generated getter for column mvUom17.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom17();

    /**
     * Generated setter for column mvUom17.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom17(String value);

    /**
     * Generated getter for column mvUom18.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom18();

    /**
     * Generated setter for column mvUom18.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom18(String value);

    /**
     * Generated getter for column mvUom19.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom19();

    /**
     * Generated setter for column mvUom19.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom19(String value);

    /**
     * Generated getter for column mvUom2.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom2();

    /**
     * Generated setter for column mvUom2.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom2(String value);

    /**
     * Generated getter for column mvUom20.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom20();

    /**
     * Generated setter for column mvUom20.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom20(String value);

    /**
     * Generated getter for column mvUom3.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom3();

    /**
     * Generated setter for column mvUom3.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom3(String value);

    /**
     * Generated getter for column mvUom4.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom4();

    /**
     * Generated setter for column mvUom4.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom4(String value);

    /**
     * Generated getter for column mvUom5.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom5();

    /**
     * Generated setter for column mvUom5.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom5(String value);

    /**
     * Generated getter for column mvUom6.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom6();

    /**
     * Generated setter for column mvUom6.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom6(String value);

    /**
     * Generated getter for column mvUom7.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom7();

    /**
     * Generated setter for column mvUom7.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom7(String value);

    /**
     * Generated getter for column mvUom8.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom8();

    /**
     * Generated setter for column mvUom8.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom8(String value);

    /**
     * Generated getter for column mvUom9.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvUom9();

    /**
     * Generated setter for column mvUom9.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvUom9(String value);

    /**
     * Generated getter for column mvValue1.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue1();

    /**
     * Generated setter for column mvValue1.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue1(String value);

    /**
     * Generated getter for column mvValue10.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue10();

    /**
     * Generated setter for column mvValue10.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue10(String value);

    /**
     * Generated getter for column mvValue11.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue11();

    /**
     * Generated setter for column mvValue11.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue11(String value);

    /**
     * Generated getter for column mvValue12.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue12();

    /**
     * Generated setter for column mvValue12.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue12(String value);

    /**
     * Generated getter for column mvValue13.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue13();

    /**
     * Generated setter for column mvValue13.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue13(String value);

    /**
     * Generated getter for column mvValue14.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue14();

    /**
     * Generated setter for column mvValue14.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue14(String value);

    /**
     * Generated getter for column mvValue15.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue15();

    /**
     * Generated setter for column mvValue15.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue15(String value);

    /**
     * Generated getter for column mvValue16.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue16();

    /**
     * Generated setter for column mvValue16.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue16(String value);

    /**
     * Generated getter for column mvValue17.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue17();

    /**
     * Generated setter for column mvValue17.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue17(String value);

    /**
     * Generated getter for column mvValue18.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue18();

    /**
     * Generated setter for column mvValue18.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue18(String value);

    /**
     * Generated getter for column mvValue19.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue19();

    /**
     * Generated setter for column mvValue19.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue19(String value);

    /**
     * Generated getter for column mvValue2.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue2();

    /**
     * Generated setter for column mvValue2.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue2(String value);

    /**
     * Generated getter for column mvValue20.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue20();

    /**
     * Generated setter for column mvValue20.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue20(String value);

    /**
     * Generated getter for column mvValue3.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue3();

    /**
     * Generated setter for column mvValue3.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue3(String value);

    /**
     * Generated getter for column mvValue4.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue4();

    /**
     * Generated setter for column mvValue4.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue4(String value);

    /**
     * Generated getter for column mvValue5.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue5();

    /**
     * Generated setter for column mvValue5.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue5(String value);

    /**
     * Generated getter for column mvValue6.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue6();

    /**
     * Generated setter for column mvValue6.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue6(String value);

    /**
     * Generated getter for column mvValue7.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue7();

    /**
     * Generated setter for column mvValue7.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue7(String value);

    /**
     * Generated getter for column mvValue8.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue8();

    /**
     * Generated setter for column mvValue8.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue8(String value);

    /**
     * Generated getter for column mvValue9.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getMvValue9();

    /**
     * Generated setter for column mvValue9.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setMvValue9(String value);

    /**
     * Generated getter for column orderNumber.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getOrderNumber();

    /**
     * Generated setter for column orderNumber.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setOrderNumber(String value);

    /**
     * Generated getter for column processFlag.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public Long getProcessFlag();

    /**
     * Generated setter for column processFlag.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setProcessFlag(Long value);

    /**
     * Generated getter for column rtPhaseKey.<BR>
     * Column description: 记录插入数据的runtime phase key
     * 
     * @return the requested value
     */
    public Long getRtPhaseKey();

    /**
     * Generated setter for column rtPhaseKey.<BR>
     * Column description: 记录插入数据的runtime phase key
     * 
     * @param value The new value to be assigned
     */
    public void setRtPhaseKey(Long value);

    /**
     * Generated getter for column sigKey.<BR>
     * Column description: 记录phase完成时签名的key,如果存在的话
     * 
     * @return the requested value
     */
    public Long getSigKey();

    /**
     * Generated setter for column sigKey.<BR>
     * Column description: 记录phase完成时签名的key,如果存在的话
     * 
     * @param value The new value to be assigned
     */
    public void setSigKey(Long value);

    /**
     * Generated getter for column stationName.<BR>
     * Column description: 工作站
     * 
     * @return the requested value
     */
    public String getStationName();

    /**
     * Generated setter for column stationName.<BR>
     * Column description: 工作站
     * 
     * @param value The new value to be assigned
     */
    public void setStationName(String value);

    /**
     * Generated getter for column stringKey1.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey1();

    /**
     * Generated setter for column stringKey1.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey1(String value);

    /**
     * Generated getter for column stringKey10.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey10();

    /**
     * Generated setter for column stringKey10.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey10(String value);

    /**
     * Generated getter for column stringKey11.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey11();

    /**
     * Generated setter for column stringKey11.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey11(String value);

    /**
     * Generated getter for column stringKey12.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey12();

    /**
     * Generated setter for column stringKey12.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey12(String value);

    /**
     * Generated getter for column stringKey13.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey13();

    /**
     * Generated setter for column stringKey13.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey13(String value);

    /**
     * Generated getter for column stringKey14.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey14();

    /**
     * Generated setter for column stringKey14.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey14(String value);

    /**
     * Generated getter for column stringKey15.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey15();

    /**
     * Generated setter for column stringKey15.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey15(String value);

    /**
     * Generated getter for column stringKey16.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey16();

    /**
     * Generated setter for column stringKey16.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey16(String value);

    /**
     * Generated getter for column stringKey17.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey17();

    /**
     * Generated setter for column stringKey17.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey17(String value);

    /**
     * Generated getter for column stringKey18.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey18();

    /**
     * Generated setter for column stringKey18.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey18(String value);

    /**
     * Generated getter for column stringKey19.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey19();

    /**
     * Generated setter for column stringKey19.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey19(String value);

    /**
     * Generated getter for column stringKey2.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey2();

    /**
     * Generated setter for column stringKey2.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey2(String value);

    /**
     * Generated getter for column stringKey20.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey20();

    /**
     * Generated setter for column stringKey20.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey20(String value);

    /**
     * Generated getter for column stringKey3.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey3();

    /**
     * Generated setter for column stringKey3.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey3(String value);

    /**
     * Generated getter for column stringKey4.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey4();

    /**
     * Generated setter for column stringKey4.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey4(String value);

    /**
     * Generated getter for column stringKey5.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey5();

    /**
     * Generated setter for column stringKey5.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey5(String value);

    /**
     * Generated getter for column stringKey6.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey6();

    /**
     * Generated setter for column stringKey6.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey6(String value);

    /**
     * Generated getter for column stringKey7.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey7();

    /**
     * Generated setter for column stringKey7.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey7(String value);

    /**
     * Generated getter for column stringKey8.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey8();

    /**
     * Generated setter for column stringKey8.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey8(String value);

    /**
     * Generated getter for column stringKey9.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringKey9();

    /**
     * Generated setter for column stringKey9.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringKey9(String value);

    /**
     * Generated getter for column stringValue1.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue1();

    /**
     * Generated setter for column stringValue1.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue1(String value);

    /**
     * Generated getter for column stringValue10.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue10();

    /**
     * Generated setter for column stringValue10.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue10(String value);

    /**
     * Generated getter for column stringValue11.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue11();

    /**
     * Generated setter for column stringValue11.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue11(String value);

    /**
     * Generated getter for column stringValue12.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue12();

    /**
     * Generated setter for column stringValue12.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue12(String value);

    /**
     * Generated getter for column stringValue13.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue13();

    /**
     * Generated setter for column stringValue13.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue13(String value);

    /**
     * Generated getter for column stringValue14.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue14();

    /**
     * Generated setter for column stringValue14.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue14(String value);

    /**
     * Generated getter for column stringValue15.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue15();

    /**
     * Generated setter for column stringValue15.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue15(String value);

    /**
     * Generated getter for column stringValue16.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue16();

    /**
     * Generated setter for column stringValue16.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue16(String value);

    /**
     * Generated getter for column stringValue17.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue17();

    /**
     * Generated setter for column stringValue17.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue17(String value);

    /**
     * Generated getter for column stringValue18.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue18();

    /**
     * Generated setter for column stringValue18.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue18(String value);

    /**
     * Generated getter for column stringValue19.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue19();

    /**
     * Generated setter for column stringValue19.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue19(String value);

    /**
     * Generated getter for column stringValue2.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue2();

    /**
     * Generated setter for column stringValue2.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue2(String value);

    /**
     * Generated getter for column stringValue20.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue20();

    /**
     * Generated setter for column stringValue20.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue20(String value);

    /**
     * Generated getter for column stringValue3.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue3();

    /**
     * Generated setter for column stringValue3.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue3(String value);

    /**
     * Generated getter for column stringValue4.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue4();

    /**
     * Generated setter for column stringValue4.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue4(String value);

    /**
     * Generated getter for column stringValue5.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue5();

    /**
     * Generated setter for column stringValue5.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue5(String value);

    /**
     * Generated getter for column stringValue6.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue6();

    /**
     * Generated setter for column stringValue6.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue6(String value);

    /**
     * Generated getter for column stringValue7.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue7();

    /**
     * Generated setter for column stringValue7.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue7(String value);

    /**
     * Generated getter for column stringValue8.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue8();

    /**
     * Generated setter for column stringValue8.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue8(String value);

    /**
     * Generated getter for column stringValue9.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStringValue9();

    /**
     * Generated setter for column stringValue9.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStringValue9(String value);

    /**
     * Generated getter for column wmsProcessFlag.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public Long getWmsProcessFlag();

    /**
     * Generated setter for column wmsProcessFlag.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setWmsProcessFlag(Long value);

}