package com.leateck.phase.sclRecordEBR0020.AT;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */

/**
 * Generated filter interface for application table SCL_IF_RecordEBRData.
 * @ftps.exclude 
 */
public interface IMESSCLIFRecordEBRDataFilter extends IMESGeneratedSCLIFRecordEBRDataFilter {
}
