package com.leateck.phase.sclRecordEBR0020.AT;


/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

/**
 * Generated class definition for application table SCL_IF_RecordEBRData.<BR>
 * Application table description: Record EBR phase同步插入改AT表用于接口处理等,避免对PhaseData表的轮询及操作
 */
public abstract class MESGeneratedSCLIFRecordEBRData extends MESATObject //
        implements IMESGeneratedSCLIFRecordEBRData {

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     * 
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedSCLIFRecordEBRData(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     * 
     * @param source The source to copy.
     */
    public MESGeneratedSCLIFRecordEBRData(MESGeneratedSCLIFRecordEBRData source) {
        super(source);
    }

    /**
     * Generated constructor
     * 
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedSCLIFRecordEBRData(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedSCLIFRecordEBRData() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }

    @Override
    public Long getErpProcessFlag() {
        return (Long) this.dgtATRow.getValue(COL_NAME_ERPPROCESSFLAG);
    }

    @Override
    public void setErpProcessFlag(Long value) {
        Long oldValue = this.getErpProcessFlag();
        this.dgtATRow.setValue(COL_NAME_ERPPROCESSFLAG, value);
        firePropertyChange(PROP_NAME_ERPPROCESSFLAG, oldValue, value);
    }

    @Override
    public String getExecuteOpr() {
        return (String) this.dgtATRow.getValue(COL_NAME_EXECUTEOPR);
    }

    @Override
    public void setExecuteOpr(String value) {
        String oldValue = this.getExecuteOpr();
        this.dgtATRow.setValue(COL_NAME_EXECUTEOPR, value);
        firePropertyChange(PROP_NAME_EXECUTEOPR, oldValue, value);
    }

    @Override
    public Long getLimsProcessFlag() {
        return (Long) this.dgtATRow.getValue(COL_NAME_LIMSPROCESSFLAG);
    }

    @Override
    public void setLimsProcessFlag(Long value) {
        Long oldValue = this.getLimsProcessFlag();
        this.dgtATRow.setValue(COL_NAME_LIMSPROCESSFLAG, value);
        firePropertyChange(PROP_NAME_LIMSPROCESSFLAG, oldValue, value);
    }

    @Override
    public Long getMesProcessFlag() {
        return (Long) this.dgtATRow.getValue(COL_NAME_MESPROCESSFLAG);
    }

    @Override
    public void setMesProcessFlag(Long value) {
        Long oldValue = this.getMesProcessFlag();
        this.dgtATRow.setValue(COL_NAME_MESPROCESSFLAG, value);
        firePropertyChange(PROP_NAME_MESPROCESSFLAG, oldValue, value);
    }

    @Override
    public String getMvKey1() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY1);
    }

    @Override
    public void setMvKey1(String value) {
        String oldValue = this.getMvKey1();
        this.dgtATRow.setValue(COL_NAME_MVKEY1, value);
        firePropertyChange(PROP_NAME_MVKEY1, oldValue, value);
    }

    @Override
    public String getMvKey10() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY10);
    }

    @Override
    public void setMvKey10(String value) {
        String oldValue = this.getMvKey10();
        this.dgtATRow.setValue(COL_NAME_MVKEY10, value);
        firePropertyChange(PROP_NAME_MVKEY10, oldValue, value);
    }

    @Override
    public String getMvKey11() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY11);
    }

    @Override
    public void setMvKey11(String value) {
        String oldValue = this.getMvKey11();
        this.dgtATRow.setValue(COL_NAME_MVKEY11, value);
        firePropertyChange(PROP_NAME_MVKEY11, oldValue, value);
    }

    @Override
    public String getMvKey12() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY12);
    }

    @Override
    public void setMvKey12(String value) {
        String oldValue = this.getMvKey12();
        this.dgtATRow.setValue(COL_NAME_MVKEY12, value);
        firePropertyChange(PROP_NAME_MVKEY12, oldValue, value);
    }

    @Override
    public String getMvKey13() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY13);
    }

    @Override
    public void setMvKey13(String value) {
        String oldValue = this.getMvKey13();
        this.dgtATRow.setValue(COL_NAME_MVKEY13, value);
        firePropertyChange(PROP_NAME_MVKEY13, oldValue, value);
    }

    @Override
    public String getMvKey14() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY14);
    }

    @Override
    public void setMvKey14(String value) {
        String oldValue = this.getMvKey14();
        this.dgtATRow.setValue(COL_NAME_MVKEY14, value);
        firePropertyChange(PROP_NAME_MVKEY14, oldValue, value);
    }

    @Override
    public String getMvKey15() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY15);
    }

    @Override
    public void setMvKey15(String value) {
        String oldValue = this.getMvKey15();
        this.dgtATRow.setValue(COL_NAME_MVKEY15, value);
        firePropertyChange(PROP_NAME_MVKEY15, oldValue, value);
    }

    @Override
    public String getMvKey16() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY16);
    }

    @Override
    public void setMvKey16(String value) {
        String oldValue = this.getMvKey16();
        this.dgtATRow.setValue(COL_NAME_MVKEY16, value);
        firePropertyChange(PROP_NAME_MVKEY16, oldValue, value);
    }

    @Override
    public String getMvKey17() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY17);
    }

    @Override
    public void setMvKey17(String value) {
        String oldValue = this.getMvKey17();
        this.dgtATRow.setValue(COL_NAME_MVKEY17, value);
        firePropertyChange(PROP_NAME_MVKEY17, oldValue, value);
    }

    @Override
    public String getMvKey18() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY18);
    }

    @Override
    public void setMvKey18(String value) {
        String oldValue = this.getMvKey18();
        this.dgtATRow.setValue(COL_NAME_MVKEY18, value);
        firePropertyChange(PROP_NAME_MVKEY18, oldValue, value);
    }

    @Override
    public String getMvKey19() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY19);
    }

    @Override
    public void setMvKey19(String value) {
        String oldValue = this.getMvKey19();
        this.dgtATRow.setValue(COL_NAME_MVKEY19, value);
        firePropertyChange(PROP_NAME_MVKEY19, oldValue, value);
    }

    @Override
    public String getMvKey2() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY2);
    }

    @Override
    public void setMvKey2(String value) {
        String oldValue = this.getMvKey2();
        this.dgtATRow.setValue(COL_NAME_MVKEY2, value);
        firePropertyChange(PROP_NAME_MVKEY2, oldValue, value);
    }

    @Override
    public String getMvKey20() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY20);
    }

    @Override
    public void setMvKey20(String value) {
        String oldValue = this.getMvKey20();
        this.dgtATRow.setValue(COL_NAME_MVKEY20, value);
        firePropertyChange(PROP_NAME_MVKEY20, oldValue, value);
    }

    @Override
    public String getMvKey3() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY3);
    }

    @Override
    public void setMvKey3(String value) {
        String oldValue = this.getMvKey3();
        this.dgtATRow.setValue(COL_NAME_MVKEY3, value);
        firePropertyChange(PROP_NAME_MVKEY3, oldValue, value);
    }

    @Override
    public String getMvKey4() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY4);
    }

    @Override
    public void setMvKey4(String value) {
        String oldValue = this.getMvKey4();
        this.dgtATRow.setValue(COL_NAME_MVKEY4, value);
        firePropertyChange(PROP_NAME_MVKEY4, oldValue, value);
    }

    @Override
    public String getMvKey5() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY5);
    }

    @Override
    public void setMvKey5(String value) {
        String oldValue = this.getMvKey5();
        this.dgtATRow.setValue(COL_NAME_MVKEY5, value);
        firePropertyChange(PROP_NAME_MVKEY5, oldValue, value);
    }

    @Override
    public String getMvKey6() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY6);
    }

    @Override
    public void setMvKey6(String value) {
        String oldValue = this.getMvKey6();
        this.dgtATRow.setValue(COL_NAME_MVKEY6, value);
        firePropertyChange(PROP_NAME_MVKEY6, oldValue, value);
    }

    @Override
    public String getMvKey7() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY7);
    }

    @Override
    public void setMvKey7(String value) {
        String oldValue = this.getMvKey7();
        this.dgtATRow.setValue(COL_NAME_MVKEY7, value);
        firePropertyChange(PROP_NAME_MVKEY7, oldValue, value);
    }

    @Override
    public String getMvKey8() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY8);
    }

    @Override
    public void setMvKey8(String value) {
        String oldValue = this.getMvKey8();
        this.dgtATRow.setValue(COL_NAME_MVKEY8, value);
        firePropertyChange(PROP_NAME_MVKEY8, oldValue, value);
    }

    @Override
    public String getMvKey9() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVKEY9);
    }

    @Override
    public void setMvKey9(String value) {
        String oldValue = this.getMvKey9();
        this.dgtATRow.setValue(COL_NAME_MVKEY9, value);
        firePropertyChange(PROP_NAME_MVKEY9, oldValue, value);
    }

    @Override
    public String getMvUom1() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM1);
    }

    @Override
    public void setMvUom1(String value) {
        String oldValue = this.getMvUom1();
        this.dgtATRow.setValue(COL_NAME_MVUOM1, value);
        firePropertyChange(PROP_NAME_MVUOM1, oldValue, value);
    }

    @Override
    public String getMvUom10() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM10);
    }

    @Override
    public void setMvUom10(String value) {
        String oldValue = this.getMvUom10();
        this.dgtATRow.setValue(COL_NAME_MVUOM10, value);
        firePropertyChange(PROP_NAME_MVUOM10, oldValue, value);
    }

    @Override
    public String getMvUom11() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM11);
    }

    @Override
    public void setMvUom11(String value) {
        String oldValue = this.getMvUom11();
        this.dgtATRow.setValue(COL_NAME_MVUOM11, value);
        firePropertyChange(PROP_NAME_MVUOM11, oldValue, value);
    }

    @Override
    public String getMvUom12() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM12);
    }

    @Override
    public void setMvUom12(String value) {
        String oldValue = this.getMvUom12();
        this.dgtATRow.setValue(COL_NAME_MVUOM12, value);
        firePropertyChange(PROP_NAME_MVUOM12, oldValue, value);
    }

    @Override
    public String getMvUom13() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM13);
    }

    @Override
    public void setMvUom13(String value) {
        String oldValue = this.getMvUom13();
        this.dgtATRow.setValue(COL_NAME_MVUOM13, value);
        firePropertyChange(PROP_NAME_MVUOM13, oldValue, value);
    }

    @Override
    public String getMvUom14() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM14);
    }

    @Override
    public void setMvUom14(String value) {
        String oldValue = this.getMvUom14();
        this.dgtATRow.setValue(COL_NAME_MVUOM14, value);
        firePropertyChange(PROP_NAME_MVUOM14, oldValue, value);
    }

    @Override
    public String getMvUom15() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM15);
    }

    @Override
    public void setMvUom15(String value) {
        String oldValue = this.getMvUom15();
        this.dgtATRow.setValue(COL_NAME_MVUOM15, value);
        firePropertyChange(PROP_NAME_MVUOM15, oldValue, value);
    }

    @Override
    public String getMvUom16() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM16);
    }

    @Override
    public void setMvUom16(String value) {
        String oldValue = this.getMvUom16();
        this.dgtATRow.setValue(COL_NAME_MVUOM16, value);
        firePropertyChange(PROP_NAME_MVUOM16, oldValue, value);
    }

    @Override
    public String getMvUom17() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM17);
    }

    @Override
    public void setMvUom17(String value) {
        String oldValue = this.getMvUom17();
        this.dgtATRow.setValue(COL_NAME_MVUOM17, value);
        firePropertyChange(PROP_NAME_MVUOM17, oldValue, value);
    }

    @Override
    public String getMvUom18() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM18);
    }

    @Override
    public void setMvUom18(String value) {
        String oldValue = this.getMvUom18();
        this.dgtATRow.setValue(COL_NAME_MVUOM18, value);
        firePropertyChange(PROP_NAME_MVUOM18, oldValue, value);
    }

    @Override
    public String getMvUom19() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM19);
    }

    @Override
    public void setMvUom19(String value) {
        String oldValue = this.getMvUom19();
        this.dgtATRow.setValue(COL_NAME_MVUOM19, value);
        firePropertyChange(PROP_NAME_MVUOM19, oldValue, value);
    }

    @Override
    public String getMvUom2() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM2);
    }

    @Override
    public void setMvUom2(String value) {
        String oldValue = this.getMvUom2();
        this.dgtATRow.setValue(COL_NAME_MVUOM2, value);
        firePropertyChange(PROP_NAME_MVUOM2, oldValue, value);
    }

    @Override
    public String getMvUom20() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM20);
    }

    @Override
    public void setMvUom20(String value) {
        String oldValue = this.getMvUom20();
        this.dgtATRow.setValue(COL_NAME_MVUOM20, value);
        firePropertyChange(PROP_NAME_MVUOM20, oldValue, value);
    }

    @Override
    public String getMvUom3() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM3);
    }

    @Override
    public void setMvUom3(String value) {
        String oldValue = this.getMvUom3();
        this.dgtATRow.setValue(COL_NAME_MVUOM3, value);
        firePropertyChange(PROP_NAME_MVUOM3, oldValue, value);
    }

    @Override
    public String getMvUom4() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM4);
    }

    @Override
    public void setMvUom4(String value) {
        String oldValue = this.getMvUom4();
        this.dgtATRow.setValue(COL_NAME_MVUOM4, value);
        firePropertyChange(PROP_NAME_MVUOM4, oldValue, value);
    }

    @Override
    public String getMvUom5() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM5);
    }

    @Override
    public void setMvUom5(String value) {
        String oldValue = this.getMvUom5();
        this.dgtATRow.setValue(COL_NAME_MVUOM5, value);
        firePropertyChange(PROP_NAME_MVUOM5, oldValue, value);
    }

    @Override
    public String getMvUom6() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM6);
    }

    @Override
    public void setMvUom6(String value) {
        String oldValue = this.getMvUom6();
        this.dgtATRow.setValue(COL_NAME_MVUOM6, value);
        firePropertyChange(PROP_NAME_MVUOM6, oldValue, value);
    }

    @Override
    public String getMvUom7() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM7);
    }

    @Override
    public void setMvUom7(String value) {
        String oldValue = this.getMvUom7();
        this.dgtATRow.setValue(COL_NAME_MVUOM7, value);
        firePropertyChange(PROP_NAME_MVUOM7, oldValue, value);
    }

    @Override
    public String getMvUom8() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM8);
    }

    @Override
    public void setMvUom8(String value) {
        String oldValue = this.getMvUom8();
        this.dgtATRow.setValue(COL_NAME_MVUOM8, value);
        firePropertyChange(PROP_NAME_MVUOM8, oldValue, value);
    }

    @Override
    public String getMvUom9() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVUOM9);
    }

    @Override
    public void setMvUom9(String value) {
        String oldValue = this.getMvUom9();
        this.dgtATRow.setValue(COL_NAME_MVUOM9, value);
        firePropertyChange(PROP_NAME_MVUOM9, oldValue, value);
    }

    @Override
    public String getMvValue1() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE1);
    }

    @Override
    public void setMvValue1(String value) {
        String oldValue = this.getMvValue1();
        this.dgtATRow.setValue(COL_NAME_MVVALUE1, value);
        firePropertyChange(PROP_NAME_MVVALUE1, oldValue, value);
    }

    @Override
    public String getMvValue10() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE10);
    }

    @Override
    public void setMvValue10(String value) {
        String oldValue = this.getMvValue10();
        this.dgtATRow.setValue(COL_NAME_MVVALUE10, value);
        firePropertyChange(PROP_NAME_MVVALUE10, oldValue, value);
    }

    @Override
    public String getMvValue11() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE11);
    }

    @Override
    public void setMvValue11(String value) {
        String oldValue = this.getMvValue11();
        this.dgtATRow.setValue(COL_NAME_MVVALUE11, value);
        firePropertyChange(PROP_NAME_MVVALUE11, oldValue, value);
    }

    @Override
    public String getMvValue12() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE12);
    }

    @Override
    public void setMvValue12(String value) {
        String oldValue = this.getMvValue12();
        this.dgtATRow.setValue(COL_NAME_MVVALUE12, value);
        firePropertyChange(PROP_NAME_MVVALUE12, oldValue, value);
    }

    @Override
    public String getMvValue13() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE13);
    }

    @Override
    public void setMvValue13(String value) {
        String oldValue = this.getMvValue13();
        this.dgtATRow.setValue(COL_NAME_MVVALUE13, value);
        firePropertyChange(PROP_NAME_MVVALUE13, oldValue, value);
    }

    @Override
    public String getMvValue14() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE14);
    }

    @Override
    public void setMvValue14(String value) {
        String oldValue = this.getMvValue14();
        this.dgtATRow.setValue(COL_NAME_MVVALUE14, value);
        firePropertyChange(PROP_NAME_MVVALUE14, oldValue, value);
    }

    @Override
    public String getMvValue15() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE15);
    }

    @Override
    public void setMvValue15(String value) {
        String oldValue = this.getMvValue15();
        this.dgtATRow.setValue(COL_NAME_MVVALUE15, value);
        firePropertyChange(PROP_NAME_MVVALUE15, oldValue, value);
    }

    @Override
    public String getMvValue16() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE16);
    }

    @Override
    public void setMvValue16(String value) {
        String oldValue = this.getMvValue16();
        this.dgtATRow.setValue(COL_NAME_MVVALUE16, value);
        firePropertyChange(PROP_NAME_MVVALUE16, oldValue, value);
    }

    @Override
    public String getMvValue17() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE17);
    }

    @Override
    public void setMvValue17(String value) {
        String oldValue = this.getMvValue17();
        this.dgtATRow.setValue(COL_NAME_MVVALUE17, value);
        firePropertyChange(PROP_NAME_MVVALUE17, oldValue, value);
    }

    @Override
    public String getMvValue18() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE18);
    }

    @Override
    public void setMvValue18(String value) {
        String oldValue = this.getMvValue18();
        this.dgtATRow.setValue(COL_NAME_MVVALUE18, value);
        firePropertyChange(PROP_NAME_MVVALUE18, oldValue, value);
    }

    @Override
    public String getMvValue19() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE19);
    }

    @Override
    public void setMvValue19(String value) {
        String oldValue = this.getMvValue19();
        this.dgtATRow.setValue(COL_NAME_MVVALUE19, value);
        firePropertyChange(PROP_NAME_MVVALUE19, oldValue, value);
    }

    @Override
    public String getMvValue2() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE2);
    }

    @Override
    public void setMvValue2(String value) {
        String oldValue = this.getMvValue2();
        this.dgtATRow.setValue(COL_NAME_MVVALUE2, value);
        firePropertyChange(PROP_NAME_MVVALUE2, oldValue, value);
    }

    @Override
    public String getMvValue20() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE20);
    }

    @Override
    public void setMvValue20(String value) {
        String oldValue = this.getMvValue20();
        this.dgtATRow.setValue(COL_NAME_MVVALUE20, value);
        firePropertyChange(PROP_NAME_MVVALUE20, oldValue, value);
    }

    @Override
    public String getMvValue3() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE3);
    }

    @Override
    public void setMvValue3(String value) {
        String oldValue = this.getMvValue3();
        this.dgtATRow.setValue(COL_NAME_MVVALUE3, value);
        firePropertyChange(PROP_NAME_MVVALUE3, oldValue, value);
    }

    @Override
    public String getMvValue4() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE4);
    }

    @Override
    public void setMvValue4(String value) {
        String oldValue = this.getMvValue4();
        this.dgtATRow.setValue(COL_NAME_MVVALUE4, value);
        firePropertyChange(PROP_NAME_MVVALUE4, oldValue, value);
    }

    @Override
    public String getMvValue5() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE5);
    }

    @Override
    public void setMvValue5(String value) {
        String oldValue = this.getMvValue5();
        this.dgtATRow.setValue(COL_NAME_MVVALUE5, value);
        firePropertyChange(PROP_NAME_MVVALUE5, oldValue, value);
    }

    @Override
    public String getMvValue6() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE6);
    }

    @Override
    public void setMvValue6(String value) {
        String oldValue = this.getMvValue6();
        this.dgtATRow.setValue(COL_NAME_MVVALUE6, value);
        firePropertyChange(PROP_NAME_MVVALUE6, oldValue, value);
    }

    @Override
    public String getMvValue7() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE7);
    }

    @Override
    public void setMvValue7(String value) {
        String oldValue = this.getMvValue7();
        this.dgtATRow.setValue(COL_NAME_MVVALUE7, value);
        firePropertyChange(PROP_NAME_MVVALUE7, oldValue, value);
    }

    @Override
    public String getMvValue8() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE8);
    }

    @Override
    public void setMvValue8(String value) {
        String oldValue = this.getMvValue8();
        this.dgtATRow.setValue(COL_NAME_MVVALUE8, value);
        firePropertyChange(PROP_NAME_MVVALUE8, oldValue, value);
    }

    @Override
    public String getMvValue9() {
        return (String) this.dgtATRow.getValue(COL_NAME_MVVALUE9);
    }

    @Override
    public void setMvValue9(String value) {
        String oldValue = this.getMvValue9();
        this.dgtATRow.setValue(COL_NAME_MVVALUE9, value);
        firePropertyChange(PROP_NAME_MVVALUE9, oldValue, value);
    }

    @Override
    public String getOrderNumber() {
        return (String) this.dgtATRow.getValue(COL_NAME_ORDERNUMBER);
    }

    @Override
    public void setOrderNumber(String value) {
        String oldValue = this.getOrderNumber();
        this.dgtATRow.setValue(COL_NAME_ORDERNUMBER, value);
        firePropertyChange(PROP_NAME_ORDERNUMBER, oldValue, value);
    }

    @Override
    public Long getProcessFlag() {
        return (Long) this.dgtATRow.getValue(COL_NAME_PROCESSFLAG);
    }

    @Override
    public void setProcessFlag(Long value) {
        Long oldValue = this.getProcessFlag();
        this.dgtATRow.setValue(COL_NAME_PROCESSFLAG, value);
        firePropertyChange(PROP_NAME_PROCESSFLAG, oldValue, value);
    }

    @Override
    public Long getRtPhaseKey() {
        return (Long) this.dgtATRow.getValue(COL_NAME_RTPHASEKEY);
    }

    @Override
    public void setRtPhaseKey(Long value) {
        Long oldValue = this.getRtPhaseKey();
        this.dgtATRow.setValue(COL_NAME_RTPHASEKEY, value);
        firePropertyChange(PROP_NAME_RTPHASEKEY, oldValue, value);
    }

    @Override
    public Long getSigKey() {
        return (Long) this.dgtATRow.getValue(COL_NAME_SIGKEY);
    }

    @Override
    public void setSigKey(Long value) {
        Long oldValue = this.getSigKey();
        this.dgtATRow.setValue(COL_NAME_SIGKEY, value);
        firePropertyChange(PROP_NAME_SIGKEY, oldValue, value);
    }

    @Override
    public String getStationName() {
        return (String) this.dgtATRow.getValue(COL_NAME_STATIONNAME);
    }

    @Override
    public void setStationName(String value) {
        String oldValue = this.getStationName();
        this.dgtATRow.setValue(COL_NAME_STATIONNAME, value);
        firePropertyChange(PROP_NAME_STATIONNAME, oldValue, value);
    }

    @Override
    public String getStringKey1() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY1);
    }

    @Override
    public void setStringKey1(String value) {
        String oldValue = this.getStringKey1();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY1, value);
        firePropertyChange(PROP_NAME_STRINGKEY1, oldValue, value);
    }

    @Override
    public String getStringKey10() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY10);
    }

    @Override
    public void setStringKey10(String value) {
        String oldValue = this.getStringKey10();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY10, value);
        firePropertyChange(PROP_NAME_STRINGKEY10, oldValue, value);
    }

    @Override
    public String getStringKey11() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY11);
    }

    @Override
    public void setStringKey11(String value) {
        String oldValue = this.getStringKey11();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY11, value);
        firePropertyChange(PROP_NAME_STRINGKEY11, oldValue, value);
    }

    @Override
    public String getStringKey12() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY12);
    }

    @Override
    public void setStringKey12(String value) {
        String oldValue = this.getStringKey12();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY12, value);
        firePropertyChange(PROP_NAME_STRINGKEY12, oldValue, value);
    }

    @Override
    public String getStringKey13() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY13);
    }

    @Override
    public void setStringKey13(String value) {
        String oldValue = this.getStringKey13();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY13, value);
        firePropertyChange(PROP_NAME_STRINGKEY13, oldValue, value);
    }

    @Override
    public String getStringKey14() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY14);
    }

    @Override
    public void setStringKey14(String value) {
        String oldValue = this.getStringKey14();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY14, value);
        firePropertyChange(PROP_NAME_STRINGKEY14, oldValue, value);
    }

    @Override
    public String getStringKey15() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY15);
    }

    @Override
    public void setStringKey15(String value) {
        String oldValue = this.getStringKey15();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY15, value);
        firePropertyChange(PROP_NAME_STRINGKEY15, oldValue, value);
    }

    @Override
    public String getStringKey16() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY16);
    }

    @Override
    public void setStringKey16(String value) {
        String oldValue = this.getStringKey16();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY16, value);
        firePropertyChange(PROP_NAME_STRINGKEY16, oldValue, value);
    }

    @Override
    public String getStringKey17() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY17);
    }

    @Override
    public void setStringKey17(String value) {
        String oldValue = this.getStringKey17();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY17, value);
        firePropertyChange(PROP_NAME_STRINGKEY17, oldValue, value);
    }

    @Override
    public String getStringKey18() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY18);
    }

    @Override
    public void setStringKey18(String value) {
        String oldValue = this.getStringKey18();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY18, value);
        firePropertyChange(PROP_NAME_STRINGKEY18, oldValue, value);
    }

    @Override
    public String getStringKey19() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY19);
    }

    @Override
    public void setStringKey19(String value) {
        String oldValue = this.getStringKey19();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY19, value);
        firePropertyChange(PROP_NAME_STRINGKEY19, oldValue, value);
    }

    @Override
    public String getStringKey2() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY2);
    }

    @Override
    public void setStringKey2(String value) {
        String oldValue = this.getStringKey2();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY2, value);
        firePropertyChange(PROP_NAME_STRINGKEY2, oldValue, value);
    }

    @Override
    public String getStringKey20() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY20);
    }

    @Override
    public void setStringKey20(String value) {
        String oldValue = this.getStringKey20();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY20, value);
        firePropertyChange(PROP_NAME_STRINGKEY20, oldValue, value);
    }

    @Override
    public String getStringKey3() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY3);
    }

    @Override
    public void setStringKey3(String value) {
        String oldValue = this.getStringKey3();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY3, value);
        firePropertyChange(PROP_NAME_STRINGKEY3, oldValue, value);
    }

    @Override
    public String getStringKey4() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY4);
    }

    @Override
    public void setStringKey4(String value) {
        String oldValue = this.getStringKey4();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY4, value);
        firePropertyChange(PROP_NAME_STRINGKEY4, oldValue, value);
    }

    @Override
    public String getStringKey5() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY5);
    }

    @Override
    public void setStringKey5(String value) {
        String oldValue = this.getStringKey5();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY5, value);
        firePropertyChange(PROP_NAME_STRINGKEY5, oldValue, value);
    }

    @Override
    public String getStringKey6() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY6);
    }

    @Override
    public void setStringKey6(String value) {
        String oldValue = this.getStringKey6();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY6, value);
        firePropertyChange(PROP_NAME_STRINGKEY6, oldValue, value);
    }

    @Override
    public String getStringKey7() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY7);
    }

    @Override
    public void setStringKey7(String value) {
        String oldValue = this.getStringKey7();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY7, value);
        firePropertyChange(PROP_NAME_STRINGKEY7, oldValue, value);
    }

    @Override
    public String getStringKey8() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY8);
    }

    @Override
    public void setStringKey8(String value) {
        String oldValue = this.getStringKey8();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY8, value);
        firePropertyChange(PROP_NAME_STRINGKEY8, oldValue, value);
    }

    @Override
    public String getStringKey9() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGKEY9);
    }

    @Override
    public void setStringKey9(String value) {
        String oldValue = this.getStringKey9();
        this.dgtATRow.setValue(COL_NAME_STRINGKEY9, value);
        firePropertyChange(PROP_NAME_STRINGKEY9, oldValue, value);
    }

    @Override
    public String getStringValue1() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE1);
    }

    @Override
    public void setStringValue1(String value) {
        String oldValue = this.getStringValue1();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE1, value);
        firePropertyChange(PROP_NAME_STRINGVALUE1, oldValue, value);
    }

    @Override
    public String getStringValue10() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE10);
    }

    @Override
    public void setStringValue10(String value) {
        String oldValue = this.getStringValue10();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE10, value);
        firePropertyChange(PROP_NAME_STRINGVALUE10, oldValue, value);
    }

    @Override
    public String getStringValue11() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE11);
    }

    @Override
    public void setStringValue11(String value) {
        String oldValue = this.getStringValue11();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE11, value);
        firePropertyChange(PROP_NAME_STRINGVALUE11, oldValue, value);
    }

    @Override
    public String getStringValue12() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE12);
    }

    @Override
    public void setStringValue12(String value) {
        String oldValue = this.getStringValue12();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE12, value);
        firePropertyChange(PROP_NAME_STRINGVALUE12, oldValue, value);
    }

    @Override
    public String getStringValue13() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE13);
    }

    @Override
    public void setStringValue13(String value) {
        String oldValue = this.getStringValue13();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE13, value);
        firePropertyChange(PROP_NAME_STRINGVALUE13, oldValue, value);
    }

    @Override
    public String getStringValue14() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE14);
    }

    @Override
    public void setStringValue14(String value) {
        String oldValue = this.getStringValue14();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE14, value);
        firePropertyChange(PROP_NAME_STRINGVALUE14, oldValue, value);
    }

    @Override
    public String getStringValue15() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE15);
    }

    @Override
    public void setStringValue15(String value) {
        String oldValue = this.getStringValue15();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE15, value);
        firePropertyChange(PROP_NAME_STRINGVALUE15, oldValue, value);
    }

    @Override
    public String getStringValue16() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE16);
    }

    @Override
    public void setStringValue16(String value) {
        String oldValue = this.getStringValue16();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE16, value);
        firePropertyChange(PROP_NAME_STRINGVALUE16, oldValue, value);
    }

    @Override
    public String getStringValue17() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE17);
    }

    @Override
    public void setStringValue17(String value) {
        String oldValue = this.getStringValue17();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE17, value);
        firePropertyChange(PROP_NAME_STRINGVALUE17, oldValue, value);
    }

    @Override
    public String getStringValue18() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE18);
    }

    @Override
    public void setStringValue18(String value) {
        String oldValue = this.getStringValue18();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE18, value);
        firePropertyChange(PROP_NAME_STRINGVALUE18, oldValue, value);
    }

    @Override
    public String getStringValue19() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE19);
    }

    @Override
    public void setStringValue19(String value) {
        String oldValue = this.getStringValue19();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE19, value);
        firePropertyChange(PROP_NAME_STRINGVALUE19, oldValue, value);
    }

    @Override
    public String getStringValue2() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE2);
    }

    @Override
    public void setStringValue2(String value) {
        String oldValue = this.getStringValue2();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE2, value);
        firePropertyChange(PROP_NAME_STRINGVALUE2, oldValue, value);
    }

    @Override
    public String getStringValue20() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE20);
    }

    @Override
    public void setStringValue20(String value) {
        String oldValue = this.getStringValue20();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE20, value);
        firePropertyChange(PROP_NAME_STRINGVALUE20, oldValue, value);
    }

    @Override
    public String getStringValue3() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE3);
    }

    @Override
    public void setStringValue3(String value) {
        String oldValue = this.getStringValue3();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE3, value);
        firePropertyChange(PROP_NAME_STRINGVALUE3, oldValue, value);
    }

    @Override
    public String getStringValue4() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE4);
    }

    @Override
    public void setStringValue4(String value) {
        String oldValue = this.getStringValue4();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE4, value);
        firePropertyChange(PROP_NAME_STRINGVALUE4, oldValue, value);
    }

    @Override
    public String getStringValue5() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE5);
    }

    @Override
    public void setStringValue5(String value) {
        String oldValue = this.getStringValue5();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE5, value);
        firePropertyChange(PROP_NAME_STRINGVALUE5, oldValue, value);
    }

    @Override
    public String getStringValue6() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE6);
    }

    @Override
    public void setStringValue6(String value) {
        String oldValue = this.getStringValue6();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE6, value);
        firePropertyChange(PROP_NAME_STRINGVALUE6, oldValue, value);
    }

    @Override
    public String getStringValue7() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE7);
    }

    @Override
    public void setStringValue7(String value) {
        String oldValue = this.getStringValue7();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE7, value);
        firePropertyChange(PROP_NAME_STRINGVALUE7, oldValue, value);
    }

    @Override
    public String getStringValue8() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE8);
    }

    @Override
    public void setStringValue8(String value) {
        String oldValue = this.getStringValue8();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE8, value);
        firePropertyChange(PROP_NAME_STRINGVALUE8, oldValue, value);
    }

    @Override
    public String getStringValue9() {
        return (String) this.dgtATRow.getValue(COL_NAME_STRINGVALUE9);
    }

    @Override
    public void setStringValue9(String value) {
        String oldValue = this.getStringValue9();
        this.dgtATRow.setValue(COL_NAME_STRINGVALUE9, value);
        firePropertyChange(PROP_NAME_STRINGVALUE9, oldValue, value);
    }

    @Override
    public Long getWmsProcessFlag() {
        return (Long) this.dgtATRow.getValue(COL_NAME_WMSPROCESSFLAG);
    }

    @Override
    public void setWmsProcessFlag(Long value) {
        Long oldValue = this.getWmsProcessFlag();
        this.dgtATRow.setValue(COL_NAME_WMSPROCESSFLAG, value);
        firePropertyChange(PROP_NAME_WMSPROCESSFLAG, oldValue, value);
    }

    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();



        return res;
    }

}