package com.leateck.phase.sclRecordEBR0020.AT;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

/**
 * Generated filter class for application table SCL_IF_RecordEBRData.
 */
public class MESSCLIFRecordEBRDataFilter extends MESGeneratedSCLIFRecordEBRDataFilter //nl
                                              implements IMESSCLIFRecordEBRDataFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESSCLIFRecordEBRDataFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESSCLIFRecordEBRDataFilter() {
        super();
    }

    /**
     * Generated method definition
     * 
     * @return the filter object
     */
    public static IMESSCLIFRecordEBRDataFilter createFilter() {
        return new MESSCLIFRecordEBRDataFilter();
    }

}