package com.leateck.phase.sclRecordEBR0020.AT;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

/**
 * Generated class definition for application table SCL_IF_RecordEBRData.
 * Application table description: Record EBR phase同步插入改AT表用于接口处理等,避免对PhaseData表的轮询及操作
 */
public class MESSCLIFRecordEBRData extends MESGeneratedSCLIFRecordEBRData //nl
                                        implements IMESSCLIFRecordEBRData {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESSCLIFRecordEBRData(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESSCLIFRecordEBRData(MESSCLIFRecordEBRData source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESSCLIFRecordEBRData(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESSCLIFRecordEBRData() {
        super();
    }

}
