package com.leateck.model.processpackitem;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;
import com.leateck.model.processpack.IMESLCProcessPack;

/**
 * Generated interface definition for application table LC_ProcessPackItem.<BR>
 * Application table description: 工艺包项表
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedLCProcessPackItem extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "LC_ProcessPackItem";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_OBJECTKEY = "objectKey";

    /** Generated column name */
    public static final String SQL_COL_NAME_OBJECTKEY = "objectKey_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_OBJECTKEY = "objectKey";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSITEMDES = "processItemDes";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSITEMDES = "processItemDes_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSITEMDES = "processItemDes";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSITEMID = "processItemId";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSITEMID = "processItemId_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSITEMID = "processItemId";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSITEMTYPE = "processItemType";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSITEMTYPE = "processItemType_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSITEMTYPE = "processItemType";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSITEMEVERSION = "processItemeVersion";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSITEMEVERSION = "processItemeVersion_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSITEMEVERSION = "processItemeVersion";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKKEY = "processPackKey";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKKEY = "processPackKey_64";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKKEY = "processPackKey";

    /**
     * Generated getter for column objectKey.<BR>
     * Column description: 工艺包项对象key
     * 
     * @return the requested value
     */
    public Long getObjectKey();

    /**
     * Generated setter for column objectKey.<BR>
     * Column description: 工艺包项对象key
     * 
     * @param value The new value to be assigned
     */
    public void setObjectKey(Long value);

    /**
     * Generated getter for column processItemDes.<BR>
     * Column description: 工艺包项描述
     * 
     * @return the requested value
     */
    public String getProcessItemDes();

    /**
     * Generated setter for column processItemDes.<BR>
     * Column description: 工艺包项描述
     * 
     * @param value The new value to be assigned
     */
    public void setProcessItemDes(String value);

    /**
     * Generated getter for column processItemId.<BR>
     * Column description: 工艺包项标识符
     * 
     * @return the requested value
     */
    public String getProcessItemId();

    /**
     * Generated setter for column processItemId.<BR>
     * Column description: 工艺包项标识符
     * 
     * @param value The new value to be assigned
     */
    public void setProcessItemId(String value);

    /**
     * Generated getter for column processItemType.<BR>
     * Column description: 工艺包项类型
     * 
     * @return the requested value
     */
    public Long getProcessItemType();

    /**
     * Generated setter for column processItemType.<BR>
     * Column description: 工艺包项类型
     * 
     * @param value The new value to be assigned
     */
    public void setProcessItemType(Long value);

    /**
     * Generated getter for column processItemeVersion.<BR>
     * Column description: 工艺包项版本
     * 
     * @return the requested value
     */
    public String getProcessItemeVersion();

    /**
     * Generated setter for column processItemeVersion.<BR>
     * Column description: 工艺包项版本
     * 
     * @param value The new value to be assigned
     */
    public void setProcessItemeVersion(String value);

    /**
     * Generated getter for column processPackKey.<BR>
     * Column description: 工艺包对象
     * 
     * @return the requested value
     */
    public IMESLCProcessPack getProcessPackKey();

    /**
     * Generated setter for column processPackKey.<BR>
     * Column description: 工艺包对象
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackKey(IMESLCProcessPack value);

}