package com.leateck.model.processpackitem;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import com.leateck.model.processpackitem.IMESLCProcessPackItem;
import com.leateck.model.processpackitem.MESGeneratedLCProcessPackItem;

/**
 * Generated class definition for application table LC_ProcessPackItem.
 * Application table description: 工艺包项表
 */
public class MESLCProcessPackItem extends MESGeneratedLCProcessPackItem //nl
                                        implements IMESLCProcessPackItem {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESLCProcessPackItem(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESLCProcessPackItem(MESLCProcessPackItem source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESLCProcessPackItem(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESLCProcessPackItem() {
        super();
    }

}
