package com.leateck.model.processPackRecord;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

import com.leateck.model.processPackRecord.IMESGeneratedLCProcessPackRecord;

/**
 * Generated interface definition for application table LC_ProcessPackRecord.
 * Application table description: <br>
 * @ftps.exclude 
 */
public interface IMESLCProcessPackRecord extends IMESGeneratedLCProcessPackRecord {
}