package com.leateck.model.processPackRecord;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.leateck.model.processPackRecord.IMESGeneratedLCProcessPackRecordFilter;

/**
 * Generated filter interface for application table LC_ProcessPackRecord.
 * @ftps.exclude 
 */
public interface IMESLCProcessPackRecordFilter extends IMESGeneratedLCProcessPackRecordFilter {
}
