package com.leateck.model.processPackRecord;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.leateck.model.processPackRecord.IMESGeneratedLCProcessPackRecord;
import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

/**
 * Generated class definition for application table LC_ProcessPackRecord.<BR>
 * Application table description: 
 */
public abstract class MESGeneratedLCProcessPackRecord extends MESATObject //
        implements IMESGeneratedLCProcessPackRecord {

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     * 
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedLCProcessPackRecord(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     * 
     * @param source The source to copy.
     */
    public MESGeneratedLCProcessPackRecord(MESGeneratedLCProcessPackRecord source) {
        super(source);
    }

    /**
     * Generated constructor
     * 
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedLCProcessPackRecord(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedLCProcessPackRecord() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }

    @Override
    public String getComments() {
        return (String) this.dgtATRow.getValue(COL_NAME_COMMENTS);
    }

    @Override
    public void setComments(String value) {
        String oldValue = this.getComments();
        this.dgtATRow.setValue(COL_NAME_COMMENTS, value);
        firePropertyChange(PROP_NAME_COMMENTS, oldValue, value);
    }

    @Override
    public String getOperator() {
        return (String) this.dgtATRow.getValue(COL_NAME_OPERATOR);
    }

    @Override
    public void setOperator(String value) {
        String oldValue = this.getOperator();
        this.dgtATRow.setValue(COL_NAME_OPERATOR, value);
        firePropertyChange(PROP_NAME_OPERATOR, oldValue, value);
    }

    @Override
    public String getProcessPackDes() {
        return (String) this.dgtATRow.getValue(COL_NAME_PROCESSPACKDES);
    }

    @Override
    public void setProcessPackDes(String value) {
        String oldValue = this.getProcessPackDes();
        this.dgtATRow.setValue(COL_NAME_PROCESSPACKDES, value);
        firePropertyChange(PROP_NAME_PROCESSPACKDES, oldValue, value);
    }

    @Override
    public String getProcessPackId() {
        return (String) this.dgtATRow.getValue(COL_NAME_PROCESSPACKID);
    }

    @Override
    public void setProcessPackId(String value) {
        String oldValue = this.getProcessPackId();
        this.dgtATRow.setValue(COL_NAME_PROCESSPACKID, value);
        firePropertyChange(PROP_NAME_PROCESSPACKID, oldValue, value);
    }

    @Override
    public Long getProcessPackState() {
        return (Long) this.dgtATRow.getValue(COL_NAME_PROCESSPACKSTATE);
    }

    @Override
    public void setProcessPackState(Long value) {
        Long oldValue = this.getProcessPackState();
        this.dgtATRow.setValue(COL_NAME_PROCESSPACKSTATE, value);
        firePropertyChange(PROP_NAME_PROCESSPACKSTATE, oldValue, value);
    }

    @Override
    public Time getStateDate() {
        return (Time) this.dgtATRow.getValue(COL_NAME_STATEDATE);
    }

    @Override
    public void setStateDate(Time value) {
        Time oldValue = this.getStateDate();
        this.dgtATRow.setValue(COL_NAME_STATEDATE, value);
        firePropertyChange(PROP_NAME_STATEDATE, oldValue, value);
    }

    @Override
    public String getVersion() {
        return (String) this.dgtATRow.getValue(COL_NAME_VERSION);
    }

    @Override
    public void setVersion(String value) {
        String oldValue = this.getVersion();
        this.dgtATRow.setValue(COL_NAME_VERSION, value);
        firePropertyChange(PROP_NAME_VERSION, oldValue, value);
    }

    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();



        return res;
    }

}