package com.leateck.model.ordermapping;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import com.leateck.model.ordermapping.IMESLCOrderMappingFilter;
import com.leateck.model.ordermapping.MESGeneratedLCOrderMappingFilter;

/**
 * Generated filter class for application table LC_OrderMapping.
 */
public class MESLCOrderMappingFilter extends MESGeneratedLCOrderMappingFilter //nl
                                              implements IMESLCOrderMappingFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESLCOrderMappingFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESLCOrderMappingFilter() {
        super();
    }

    /**
     * Generated method definition
     * 
     * @return the filter object
     */
    public static IMESLCOrderMappingFilter createFilter() {
        return new MESLCOrderMappingFilter();
    }

}