package com.leateck.model.processpack;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table LC_ProcessPack.<BR>
 * Application table description: 工艺包信息表
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedLCProcessPack extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "LC_ProcessPack";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_CREATETIME = "createTime";

    /** Generated column name */
    public static final String SQL_COL_NAME_CREATETIME_UTC = "createTime_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CREATETIME = "createTime";

    /** Generated property name */
    public static final String PROP_NAME_ENTRYTIME = "entryTime";

    /** Generated column name */
    public static final String SQL_COL_NAME_ENTRYTIME_UTC = "entryTime_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_ENTRYTIME = "entryTime";

    /** Generated property name */
    public static final String PROP_NAME_ISLOCK = "isLock";

    /** Generated column name */
    public static final String SQL_COL_NAME_ISLOCK = "isLock_Y";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_ISLOCK = "isLock";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKDES = "processPackDes";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKDES = "processPackDes_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKDES = "processPackDes";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKID = "processPackId";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKID = "processPackId_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKID = "processPackId";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSPACKSTATE = "processPackState";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSPACKSTATE = "processPackState_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSPACKSTATE = "processPackState";

    /** Generated property name */
    public static final String PROP_NAME_VERSION = "version";

    /** Generated column name */
    public static final String SQL_COL_NAME_VERSION = "version_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_VERSION = "version";

    /**
     * Generated getter for column createTime.<BR>
     * Column description: 工艺包创建时间
     * 
     * @return the requested value
     */
    public Time getCreateTime();

    /**
     * Generated setter for column createTime.<BR>
     * Column description: 工艺包创建时间
     * 
     * @param value The new value to be assigned
     */
    public void setCreateTime(Time value);

    /**
     * Generated getter for column entryTime.<BR>
     * Column description: 工艺包生效时间
     * 
     * @return the requested value
     */
    public Time getEntryTime();

    /**
     * Generated setter for column entryTime.<BR>
     * Column description: 工艺包生效时间
     * 
     * @param value The new value to be assigned
     */
    public void setEntryTime(Time value);

    /**
     * Generated getter for column isLock.<BR>
     * Column description: 是否锁定
     * 
     * @return the requested value
     */
    public Boolean getIsLock();

    /**
     * Generated setter for column isLock.<BR>
     * Column description: 是否锁定
     * 
     * @param value The new value to be assigned
     */
    public void setIsLock(Boolean value);

    /**
     * Generated getter for column processPackDes.<BR>
     * Column description: 工艺包描述
     * 
     * @return the requested value
     */
    public String getProcessPackDes();

    /**
     * Generated setter for column processPackDes.<BR>
     * Column description: 工艺包描述
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackDes(String value);

    /**
     * Generated getter for column processPackId.<BR>
     * Column description: 工艺包标识符
     * 
     * @return the requested value
     */
    public String getProcessPackId();

    /**
     * Generated setter for column processPackId.<BR>
     * Column description: 工艺包标识符
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackId(String value);

    /**
     * Generated getter for column processPackState.<BR>
     * Column description: 状态
     * 
     * @return the requested value
     */
    public Long getProcessPackState();

    /**
     * Generated setter for column processPackState.<BR>
     * Column description: 状态
     * 
     * @param value The new value to be assigned
     */
    public void setProcessPackState(Long value);

    /**
     * Generated getter for column version.<BR>
     * Column description: 版本
     * 
     * @return the requested value
     */
    public String getVersion();

    /**
     * Generated setter for column version.<BR>
     * Column description: 版本
     * 
     * @param value The new value to be assigned
     */
    public void setVersion(String value);

}