package com.leateck.model.processpack;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import com.leateck.model.processpack.IMESLCProcessPack;
import com.leateck.model.processpack.MESGeneratedLCProcessPack;

/**
 * Generated class definition for application table LC_ProcessPack.
 * Application table description: 工艺包信息表
 */
public class MESLCProcessPack extends MESGeneratedLCProcessPack //nl
                                        implements IMESLCProcessPack {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESLCProcessPack(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESLCProcessPack(MESLCProcessPack source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESLCProcessPack(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESLCProcessPack() {
        super();
    }

}
