package com.leateck.model.messagetemplate;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */


/**
 * Generated interface definition for application table LC_MessageTemplate.
 * Application table description: 消息模板配置表<br>
 * @ftps.exclude 
 */
public interface IMESLCMessageTemplate extends IMESGeneratedLCMessageTemplate {
}