package com.leateck.model.messagetemplate;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.client.MeasuredValue;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table LC_MessageTemplate.<BR>
 * Application table description: 消息模板配置表
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedLCMessageTemplate extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "LC_MessageTemplate";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_CODENAME = "codeName";

    /** Generated column name */
    public static final String SQL_COL_NAME_CODENAME = "codeName_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CODENAME = "codeName";

    /** Generated property name */
    public static final String PROP_NAME_CRITICALTIME = "criticalTime";

    /** Generated column name */
    public static final String SQL_COL_NAME_CRITICALTIME = "criticalTime_V";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CRITICALTIME = "criticalTime";

    /** Generated property name */
    public static final String PROP_NAME_CUSTOMMESSAGE = "customMessage";

    /** Generated column name */
    public static final String SQL_COL_NAME_CUSTOMMESSAGE = "customMessage_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CUSTOMMESSAGE = "customMessage";

    /** Generated property name */
    public static final String PROP_NAME_MESSAGEID = "messageId";

    /** Generated column name */
    public static final String SQL_COL_NAME_MESSAGEID = "messageId_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MESSAGEID = "messageId";

    /** Generated property name */
    public static final String PROP_NAME_STATUS = "status";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATUS = "status_Y";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STATUS = "status";

    /** Generated property name */
    public static final String PROP_NAME_TEMPLATETYPE = "templateType";

    /** Generated column name */
    public static final String SQL_COL_NAME_TEMPLATETYPE = "templateType_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_TEMPLATETYPE = "templateType";

    /** Generated property name */
    public static final String PROP_NAME_USER = "user";

    /** Generated column name */
    public static final String SQL_COL_NAME_USER = "user_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_USER = "user";

    /** Generated property name */
    public static final String PROP_NAME_USERGROUP = "userGroup";

    /** Generated column name */
    public static final String SQL_COL_NAME_USERGROUP = "userGroup_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_USERGROUP = "userGroup";

    /**
     * Generated getter for column codeName.<BR>
     * Column description: 代码/名称
     * 
     * @return the requested value
     */
    public String getCodeName();

    /**
     * Generated setter for column codeName.<BR>
     * Column description: 代码/名称
     * 
     * @param value The new value to be assigned
     */
    public void setCodeName(String value);

    /**
     * Generated getter for column criticalTime.<BR>
     * Column description: 临期时间
     * 
     * @return the requested value
     */
    public MeasuredValue getCriticalTime();

    /**
     * Generated setter for column criticalTime.<BR>
     * Column description: 临期时间
     * 
     * @param value The new value to be assigned
     */
    public void setCriticalTime(MeasuredValue value);

    /**
     * Generated getter for column customMessage.<BR>
     * Column description: 自定义消息
     * 
     * @return the requested value
     */
    public String getCustomMessage();

    /**
     * Generated setter for column customMessage.<BR>
     * Column description: 自定义消息
     * 
     * @param value The new value to be assigned
     */
    public void setCustomMessage(String value);

    /**
     * Generated getter for column messageId.<BR>
     * Column description: 消息代码
     * 
     * @return the requested value
     */
    public String getMessageId();

    /**
     * Generated setter for column messageId.<BR>
     * Column description: 消息代码
     * 
     * @param value The new value to be assigned
     */
    public void setMessageId(String value);

    /**
     * Generated getter for column status.<BR>
     * Column description: 状态
     * 
     * @return the requested value
     */
    public Boolean getStatus();

    /**
     * Generated setter for column status.<BR>
     * Column description: 状态
     * 
     * @param value The new value to be assigned
     */
    public void setStatus(Boolean value);

    /**
     * Generated getter for column templateType.<BR>
     * Column description: 模板标识
     * 
     * @return the requested value
     */
    public Long getTemplateType();

    /**
     * Generated setter for column templateType.<BR>
     * Column description: 模板标识
     * 
     * @param value The new value to be assigned
     */
    public void setTemplateType(Long value);

    /**
     * Generated getter for column user.<BR>
     * Column description: 用户
     * 
     * @return the requested value
     */
    public String getUser();

    /**
     * Generated setter for column user.<BR>
     * Column description: 用户
     * 
     * @param value The new value to be assigned
     */
    public void setUser(String value);

    /**
     * Generated getter for column userGroup.<BR>
     * Column description: 用户组
     * 
     * @return the requested value
     */
    public String getUserGroup();

    /**
     * Generated setter for column userGroup.<BR>
     * Column description: 用户组
     * 
     * @param value The new value to be assigned
     */
    public void setUserGroup(String value);

}