package com.leateck.model.messagetemplate;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;


/**
 * Generated filter class for application table LC_MessageTemplate.
 */
public class MESLCMessageTemplateFilter extends MESGeneratedLCMessageTemplateFilter //nl
                                              implements IMESLCMessageTemplateFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESLCMessageTemplateFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESLCMessageTemplateFilter() {
        super();
    }

    /**
     * Generated method definition
     * 
     * @return the filter object
     */
    public static IMESLCMessageTemplateFilter createFilter() {
        return new MESLCMessageTemplateFilter();
    }

}