package com.leateck.phase.materialproduction0010;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutput;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputLCMatProduce0010 extends MESGeneratedRtPhaseOutputLCMatProduce0010 implements IMESRtPhaseOutput {

    /**
     * Generated constructor (from DB key)
     *
     * @param key The key of the ATRow to load.
     */
    public MESRtPhaseOutputLCMatProduce0010(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESRtPhaseOutputLCMatProduce0010(MESRtPhaseOutputLCMatProduce0010 source) {
        super(source);
    }

    /**
     * Generated constructor (from ATRow)
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESRtPhaseOutputLCMatProduce0010(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESRtPhaseOutputLCMatProduce0010() {
        super();
    }

}
