package com.leateck.commons.materiaInventoryImport.entity;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */


/**
 * Generated interface definition for application table CD_MateriaInventoryImport.
 * Application table description: <br>
 * @ftps.exclude 
 */
public interface IMESCDMateriaInventoryImport extends IMESGeneratedCDMateriaInventoryImport {
}