package com.leateck.commons.materiaInventoryImport.entity;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

/**
 * Generated class definition for application table CD_MateriaInventorySublot.
 * Application table description: 
 */
public class MESCDMateriaInventorySublot extends MESGeneratedCDMateriaInventorySublot //nl
                                        implements IMESCDMateriaInventorySublot {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESCDMateriaInventorySublot(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESCDMateriaInventorySublot(MESCDMateriaInventorySublot source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESCDMateriaInventorySublot(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESCDMateriaInventorySublot() {
        super();
    }

}
