package com.leateck.model.userProcessPack;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.leateck.model.userProcessPack.IMESGeneratedLCUserProcessPackFilter;

/**
 * Generated filter interface for application table LC_UserProcessPack.
 * @ftps.exclude 
 */
public interface IMESLCUserProcessPackFilter extends IMESGeneratedLCUserProcessPackFilter {
}
