package com.leateck.model.orderobject;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.leateck.model.orderobject.IMESGeneratedLCOrderObject;
import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

/**
 * Generated class definition for application table LC_OrderObject.<BR>
 * Application table description: 
 */
public abstract class MESGeneratedLCOrderObject extends MESATObject //
        implements IMESGeneratedLCOrderObject {

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     * 
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedLCOrderObject(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     * 
     * @param source The source to copy.
     */
    public MESGeneratedLCOrderObject(MESGeneratedLCOrderObject source) {
        super(source);
    }

    /**
     * Generated constructor
     * 
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedLCOrderObject(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedLCOrderObject() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }

    @Override
    public String getBatchno() {
        return (String) this.dgtATRow.getValue(COL_NAME_BATCHNO);
    }

    @Override
    public void setBatchno(String value) {
        String oldValue = this.getBatchno();
        this.dgtATRow.setValue(COL_NAME_BATCHNO, value);
        firePropertyChange(PROP_NAME_BATCHNO, oldValue, value);
    }

    @Override
    public String getOrderno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ORDERNO);
    }

    @Override
    public void setOrderno(String value) {
        String oldValue = this.getOrderno();
        this.dgtATRow.setValue(COL_NAME_ORDERNO, value);
        firePropertyChange(PROP_NAME_ORDERNO, oldValue, value);
    }

    @Override
    public String getPartno() {
        return (String) this.dgtATRow.getValue(COL_NAME_PARTNO);
    }

    @Override
    public void setPartno(String value) {
        String oldValue = this.getPartno();
        this.dgtATRow.setValue(COL_NAME_PARTNO, value);
        firePropertyChange(PROP_NAME_PARTNO, oldValue, value);
    }

    @Override
    public String getRecipeno() {
        return (String) this.dgtATRow.getValue(COL_NAME_RECIPENO);
    }

    @Override
    public void setRecipeno(String value) {
        String oldValue = this.getRecipeno();
        this.dgtATRow.setValue(COL_NAME_RECIPENO, value);
        firePropertyChange(PROP_NAME_RECIPENO, oldValue, value);
    }

    @Override
    public String getType() {
        return (String) this.dgtATRow.getValue(COL_NAME_TYPE);
    }

    @Override
    public void setType(String value) {
        String oldValue = this.getType();
        this.dgtATRow.setValue(COL_NAME_TYPE, value);
        firePropertyChange(PROP_NAME_TYPE, oldValue, value);
    }

    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();



        return res;
    }

}