package com.leateck.phase.materialalternativeidentification0010;

/**
 * This file is generated by the PhaseLibManager
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseDataFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseDataMatAlterIdent0010Filter extends MESGeneratedRtPhaseDataMatAlterIdent0010Filter //nl
        implements IMESRtPhaseDataFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseDataMatAlterIdent0010Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseDataMatAlterIdent0010Filter() {
        super();
    }
}
