package com.leateck.model.locationFilterObject;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;



/**
 * Generated interface definition for application table LC_LocationFilterObject.
 * Application table description: <br>
 * @ftps.exclude 
 */
public interface IMESLCLocationFilterObject extends IMESGeneratedLCLocationFilterObject {
}