package com.leateck.model.locationFilterObject;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table LC_LocationFilterObject.<BR>
 * Application table description: 
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedLCLocationFilterObject extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "LC_LocationFilterObject";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_LOCATION = "location";

    /** Generated column name */
    public static final String SQL_COL_NAME_LOCATION = "location_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_LOCATION = "location";

    /** Generated property name */
    public static final String PROP_NAME_LOCATIONDESC = "locationDesc";

    /** Generated column name */
    public static final String SQL_COL_NAME_LOCATIONDESC = "locationDesc_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_LOCATIONDESC = "locationDesc";

    /** Generated property name */
    public static final String PROP_NAME_STORAGEAREA = "storageArea";

    /** Generated column name */
    public static final String SQL_COL_NAME_STORAGEAREA = "StorageArea_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STORAGEAREA = "StorageArea";

    /** Generated property name */
    public static final String PROP_NAME_STORAGEAREADESC = "storageAreaDesc";

    /** Generated column name */
    public static final String SQL_COL_NAME_STORAGEAREADESC = "StorageAreaDesc_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STORAGEAREADESC = "StorageAreaDesc";

    /** Generated property name */
    public static final String PROP_NAME_WAREHOUSE = "warehouse";

    /** Generated column name */
    public static final String SQL_COL_NAME_WAREHOUSE = "warehouse_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_WAREHOUSE = "warehouse";

    /** Generated property name */
    public static final String PROP_NAME_WAREHOUSEDESC = "warehouseDesc";

    /** Generated column name */
    public static final String SQL_COL_NAME_WAREHOUSEDESC = "warehouseDesc_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_WAREHOUSEDESC = "warehouseDesc";

    /**
     * Generated getter for column location.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getLocation();

    /**
     * Generated setter for column location.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setLocation(String value);

    /**
     * Generated getter for column locationDesc.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getLocationDesc();

    /**
     * Generated setter for column locationDesc.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setLocationDesc(String value);

    /**
     * Generated getter for column StorageArea.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStorageArea();

    /**
     * Generated setter for column StorageArea.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStorageArea(String value);

    /**
     * Generated getter for column StorageAreaDesc.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getStorageAreaDesc();

    /**
     * Generated setter for column StorageAreaDesc.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setStorageAreaDesc(String value);

    /**
     * Generated getter for column warehouse.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getWarehouse();

    /**
     * Generated setter for column warehouse.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setWarehouse(String value);

    /**
     * Generated getter for column warehouseDesc.<BR>
     * Column description: 
     * 
     * @return the requested value
     */
    public String getWarehouseDesc();

    /**
     * Generated setter for column warehouseDesc.<BR>
     * Column description: 
     * 
     * @param value The new value to be assigned
     */
    public void setWarehouseDesc(String value);

}