package com.leateck.model.locationFilterObject;


/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;



/**
 * Generated class definition for application table LC_LocationFilterObject.
 * Application table description: 
 */
public class MESLCLocationFilterObject extends MESGeneratedLCLocationFilterObject //nl
                                        implements IMESLCLocationFilterObject {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESLCLocationFilterObject(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESLCLocationFilterObject(MESLCLocationFilterObject source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESLCLocationFilterObject(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESLCLocationFilterObject() {
        super();
    }

}
